package com.citicup.model;

import java.io.Serializable;

public class AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车企业三年销售平均增长率.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车企业三年销售平均增长率.thrYearSalesGrowRateComAve
     *
     * @mbggenerated
     */
    private String thryearsalesgrowratecomave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车企业三年销售平均增长率.year
     *
     * @return the value of 中国汽车企业三年销售平均增长率.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车企业三年销售平均增长率.year
     *
     * @param year the value for 中国汽车企业三年销售平均增长率.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车企业三年销售平均增长率.thrYearSalesGrowRateComAve
     *
     * @return the value of 中国汽车企业三年销售平均增长率.thrYearSalesGrowRateComAve
     *
     * @mbggenerated
     */
    public String getThryearsalesgrowratecomave() {
        return thryearsalesgrowratecomave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车企业三年销售平均增长率.thrYearSalesGrowRateComAve
     *
     * @param thryearsalesgrowratecomave the value for 中国汽车企业三年销售平均增长率.thrYearSalesGrowRateComAve
     *
     * @mbggenerated
     */
    public void setThryearsalesgrowratecomave(String thryearsalesgrowratecomave) {
        this.thryearsalesgrowratecomave = thryearsalesgrowratecomave == null ? null : thryearsalesgrowratecomave.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises other = (AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises) that;
        return (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getThryearsalesgrowratecomave() == null ? other.getThryearsalesgrowratecomave() == null : this.getThryearsalesgrowratecomave().equals(other.getThryearsalesgrowratecomave()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getThryearsalesgrowratecomave() == null) ? 0 : getThryearsalesgrowratecomave().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", year=").append(year);
        sb.append(", thryearsalesgrowratecomave=").append(thryearsalesgrowratecomave);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}