package com.citicup.model;

import java.io.Serializable;

public class ChineseCommercialVehicleSalesDividedByType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.coachSalesCHN
     *
     * @mbggenerated
     */
    private String coachsaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.truckSalesCHN
     *
     * @mbggenerated
     */
    private String trucksaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.semiSalesCHN
     *
     * @mbggenerated
     */
    private String semisaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.imcomplcoachSalesCHN
     *
     * @mbggenerated
     */
    private String imcomplcoachsaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分车型销量.incompltruckSalesCHN
     *
     * @mbggenerated
     */
    private String incompltrucksaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国商用车分车型销量
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.f1
     *
     * @return the value of 中国商用车分车型销量.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.f1
     *
     * @param f1 the value for 中国商用车分车型销量.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.coachSalesCHN
     *
     * @return the value of 中国商用车分车型销量.coachSalesCHN
     *
     * @mbggenerated
     */
    public String getCoachsaleschn() {
        return coachsaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.coachSalesCHN
     *
     * @param coachsaleschn the value for 中国商用车分车型销量.coachSalesCHN
     *
     * @mbggenerated
     */
    public void setCoachsaleschn(String coachsaleschn) {
        this.coachsaleschn = coachsaleschn == null ? null : coachsaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.truckSalesCHN
     *
     * @return the value of 中国商用车分车型销量.truckSalesCHN
     *
     * @mbggenerated
     */
    public String getTrucksaleschn() {
        return trucksaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.truckSalesCHN
     *
     * @param trucksaleschn the value for 中国商用车分车型销量.truckSalesCHN
     *
     * @mbggenerated
     */
    public void setTrucksaleschn(String trucksaleschn) {
        this.trucksaleschn = trucksaleschn == null ? null : trucksaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.semiSalesCHN
     *
     * @return the value of 中国商用车分车型销量.semiSalesCHN
     *
     * @mbggenerated
     */
    public String getSemisaleschn() {
        return semisaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.semiSalesCHN
     *
     * @param semisaleschn the value for 中国商用车分车型销量.semiSalesCHN
     *
     * @mbggenerated
     */
    public void setSemisaleschn(String semisaleschn) {
        this.semisaleschn = semisaleschn == null ? null : semisaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.imcomplcoachSalesCHN
     *
     * @return the value of 中国商用车分车型销量.imcomplcoachSalesCHN
     *
     * @mbggenerated
     */
    public String getImcomplcoachsaleschn() {
        return imcomplcoachsaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.imcomplcoachSalesCHN
     *
     * @param imcomplcoachsaleschn the value for 中国商用车分车型销量.imcomplcoachSalesCHN
     *
     * @mbggenerated
     */
    public void setImcomplcoachsaleschn(String imcomplcoachsaleschn) {
        this.imcomplcoachsaleschn = imcomplcoachsaleschn == null ? null : imcomplcoachsaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分车型销量.incompltruckSalesCHN
     *
     * @return the value of 中国商用车分车型销量.incompltruckSalesCHN
     *
     * @mbggenerated
     */
    public String getIncompltrucksaleschn() {
        return incompltrucksaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分车型销量.incompltruckSalesCHN
     *
     * @param incompltrucksaleschn the value for 中国商用车分车型销量.incompltruckSalesCHN
     *
     * @mbggenerated
     */
    public void setIncompltrucksaleschn(String incompltrucksaleschn) {
        this.incompltrucksaleschn = incompltrucksaleschn == null ? null : incompltrucksaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分车型销量
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChineseCommercialVehicleSalesDividedByType other = (ChineseCommercialVehicleSalesDividedByType) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getCoachsaleschn() == null ? other.getCoachsaleschn() == null : this.getCoachsaleschn().equals(other.getCoachsaleschn()))
            && (this.getTrucksaleschn() == null ? other.getTrucksaleschn() == null : this.getTrucksaleschn().equals(other.getTrucksaleschn()))
            && (this.getSemisaleschn() == null ? other.getSemisaleschn() == null : this.getSemisaleschn().equals(other.getSemisaleschn()))
            && (this.getImcomplcoachsaleschn() == null ? other.getImcomplcoachsaleschn() == null : this.getImcomplcoachsaleschn().equals(other.getImcomplcoachsaleschn()))
            && (this.getIncompltrucksaleschn() == null ? other.getIncompltrucksaleschn() == null : this.getIncompltrucksaleschn().equals(other.getIncompltrucksaleschn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分车型销量
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getCoachsaleschn() == null) ? 0 : getCoachsaleschn().hashCode());
        result = prime * result + ((getTrucksaleschn() == null) ? 0 : getTrucksaleschn().hashCode());
        result = prime * result + ((getSemisaleschn() == null) ? 0 : getSemisaleschn().hashCode());
        result = prime * result + ((getImcomplcoachsaleschn() == null) ? 0 : getImcomplcoachsaleschn().hashCode());
        result = prime * result + ((getIncompltrucksaleschn() == null) ? 0 : getIncompltrucksaleschn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分车型销量
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", coachsaleschn=").append(coachsaleschn);
        sb.append(", trucksaleschn=").append(trucksaleschn);
        sb.append(", semisaleschn=").append(semisaleschn);
        sb.append(", imcomplcoachsaleschn=").append(imcomplcoachsaleschn);
        sb.append(", incompltrucksaleschn=").append(incompltrucksaleschn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}