package com.citicup.model;

import java.io.Serializable;

public class ChineseCommercialVehicleSalesDividedByFuel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分燃料类型销量.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分燃料类型销量.comdieselSalesCHN
     *
     * @mbggenerated
     */
    private String comdieselsaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分燃料类型销量.comgasSalesCHN
     *
     * @mbggenerated
     */
    private String comgassaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国商用车分燃料类型销量.comotherFuelSalesCHN
     *
     * @mbggenerated
     */
    private String comotherfuelsaleschn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国商用车分燃料类型销量
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分燃料类型销量.f1
     *
     * @return the value of 中国商用车分燃料类型销量.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分燃料类型销量.f1
     *
     * @param f1 the value for 中国商用车分燃料类型销量.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分燃料类型销量.comdieselSalesCHN
     *
     * @return the value of 中国商用车分燃料类型销量.comdieselSalesCHN
     *
     * @mbggenerated
     */
    public String getComdieselsaleschn() {
        return comdieselsaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分燃料类型销量.comdieselSalesCHN
     *
     * @param comdieselsaleschn the value for 中国商用车分燃料类型销量.comdieselSalesCHN
     *
     * @mbggenerated
     */
    public void setComdieselsaleschn(String comdieselsaleschn) {
        this.comdieselsaleschn = comdieselsaleschn == null ? null : comdieselsaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分燃料类型销量.comgasSalesCHN
     *
     * @return the value of 中国商用车分燃料类型销量.comgasSalesCHN
     *
     * @mbggenerated
     */
    public String getComgassaleschn() {
        return comgassaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分燃料类型销量.comgasSalesCHN
     *
     * @param comgassaleschn the value for 中国商用车分燃料类型销量.comgasSalesCHN
     *
     * @mbggenerated
     */
    public void setComgassaleschn(String comgassaleschn) {
        this.comgassaleschn = comgassaleschn == null ? null : comgassaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国商用车分燃料类型销量.comotherFuelSalesCHN
     *
     * @return the value of 中国商用车分燃料类型销量.comotherFuelSalesCHN
     *
     * @mbggenerated
     */
    public String getComotherfuelsaleschn() {
        return comotherfuelsaleschn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国商用车分燃料类型销量.comotherFuelSalesCHN
     *
     * @param comotherfuelsaleschn the value for 中国商用车分燃料类型销量.comotherFuelSalesCHN
     *
     * @mbggenerated
     */
    public void setComotherfuelsaleschn(String comotherfuelsaleschn) {
        this.comotherfuelsaleschn = comotherfuelsaleschn == null ? null : comotherfuelsaleschn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分燃料类型销量
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChineseCommercialVehicleSalesDividedByFuel other = (ChineseCommercialVehicleSalesDividedByFuel) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getComdieselsaleschn() == null ? other.getComdieselsaleschn() == null : this.getComdieselsaleschn().equals(other.getComdieselsaleschn()))
            && (this.getComgassaleschn() == null ? other.getComgassaleschn() == null : this.getComgassaleschn().equals(other.getComgassaleschn()))
            && (this.getComotherfuelsaleschn() == null ? other.getComotherfuelsaleschn() == null : this.getComotherfuelsaleschn().equals(other.getComotherfuelsaleschn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分燃料类型销量
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getComdieselsaleschn() == null) ? 0 : getComdieselsaleschn().hashCode());
        result = prime * result + ((getComgassaleschn() == null) ? 0 : getComgassaleschn().hashCode());
        result = prime * result + ((getComotherfuelsaleschn() == null) ? 0 : getComotherfuelsaleschn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国商用车分燃料类型销量
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", comdieselsaleschn=").append(comdieselsaleschn);
        sb.append(", comgassaleschn=").append(comgassaleschn);
        sb.append(", comotherfuelsaleschn=").append(comotherfuelsaleschn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}