package com.citicup.model;

import java.io.Serializable;

public class ChineseAutoProduction implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车产量.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车产量.yieldCHN
     *
     * @mbggenerated
     */
    private String yieldchn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国汽车产量
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车产量.f1
     *
     * @return the value of 中国汽车产量.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车产量.f1
     *
     * @param f1 the value for 中国汽车产量.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车产量.yieldCHN
     *
     * @return the value of 中国汽车产量.yieldCHN
     *
     * @mbggenerated
     */
    public String getYieldchn() {
        return yieldchn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车产量.yieldCHN
     *
     * @param yieldchn the value for 中国汽车产量.yieldCHN
     *
     * @mbggenerated
     */
    public void setYieldchn(String yieldchn) {
        this.yieldchn = yieldchn == null ? null : yieldchn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车产量
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChineseAutoProduction other = (ChineseAutoProduction) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getYieldchn() == null ? other.getYieldchn() == null : this.getYieldchn().equals(other.getYieldchn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车产量
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getYieldchn() == null) ? 0 : getYieldchn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车产量
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", yieldchn=").append(yieldchn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}