package com.citicup.model;

import java.io.Serializable;

public class ChineseAutoIndustryNewCapacity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业新增产能.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业新增产能.basicNewCap
     *
     * @mbggenerated
     */
    private String basicnewcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业新增产能.coachNewCap
     *
     * @mbggenerated
     */
    private String coachnewcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业新增产能.truckNewCap
     *
     * @mbggenerated
     */
    private String trucknewcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业新增产能.otherNewCap
     *
     * @mbggenerated
     */
    private String othernewcap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国汽车行业新增产能
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业新增产能.f1
     *
     * @return the value of 中国汽车行业新增产能.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业新增产能.f1
     *
     * @param f1 the value for 中国汽车行业新增产能.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业新增产能.basicNewCap
     *
     * @return the value of 中国汽车行业新增产能.basicNewCap
     *
     * @mbggenerated
     */
    public String getBasicnewcap() {
        return basicnewcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业新增产能.basicNewCap
     *
     * @param basicnewcap the value for 中国汽车行业新增产能.basicNewCap
     *
     * @mbggenerated
     */
    public void setBasicnewcap(String basicnewcap) {
        this.basicnewcap = basicnewcap == null ? null : basicnewcap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业新增产能.coachNewCap
     *
     * @return the value of 中国汽车行业新增产能.coachNewCap
     *
     * @mbggenerated
     */
    public String getCoachnewcap() {
        return coachnewcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业新增产能.coachNewCap
     *
     * @param coachnewcap the value for 中国汽车行业新增产能.coachNewCap
     *
     * @mbggenerated
     */
    public void setCoachnewcap(String coachnewcap) {
        this.coachnewcap = coachnewcap == null ? null : coachnewcap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业新增产能.truckNewCap
     *
     * @return the value of 中国汽车行业新增产能.truckNewCap
     *
     * @mbggenerated
     */
    public String getTrucknewcap() {
        return trucknewcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业新增产能.truckNewCap
     *
     * @param trucknewcap the value for 中国汽车行业新增产能.truckNewCap
     *
     * @mbggenerated
     */
    public void setTrucknewcap(String trucknewcap) {
        this.trucknewcap = trucknewcap == null ? null : trucknewcap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业新增产能.otherNewCap
     *
     * @return the value of 中国汽车行业新增产能.otherNewCap
     *
     * @mbggenerated
     */
    public String getOthernewcap() {
        return othernewcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业新增产能.otherNewCap
     *
     * @param othernewcap the value for 中国汽车行业新增产能.otherNewCap
     *
     * @mbggenerated
     */
    public void setOthernewcap(String othernewcap) {
        this.othernewcap = othernewcap == null ? null : othernewcap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业新增产能
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChineseAutoIndustryNewCapacity other = (ChineseAutoIndustryNewCapacity) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getBasicnewcap() == null ? other.getBasicnewcap() == null : this.getBasicnewcap().equals(other.getBasicnewcap()))
            && (this.getCoachnewcap() == null ? other.getCoachnewcap() == null : this.getCoachnewcap().equals(other.getCoachnewcap()))
            && (this.getTrucknewcap() == null ? other.getTrucknewcap() == null : this.getTrucknewcap().equals(other.getTrucknewcap()))
            && (this.getOthernewcap() == null ? other.getOthernewcap() == null : this.getOthernewcap().equals(other.getOthernewcap()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业新增产能
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getBasicnewcap() == null) ? 0 : getBasicnewcap().hashCode());
        result = prime * result + ((getCoachnewcap() == null) ? 0 : getCoachnewcap().hashCode());
        result = prime * result + ((getTrucknewcap() == null) ? 0 : getTrucknewcap().hashCode());
        result = prime * result + ((getOthernewcap() == null) ? 0 : getOthernewcap().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业新增产能
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", basicnewcap=").append(basicnewcap);
        sb.append(", coachnewcap=").append(coachnewcap);
        sb.append(", trucknewcap=").append(trucknewcap);
        sb.append(", othernewcap=").append(othernewcap);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}