package com.citicup.model;

import java.io.Serializable;

public class ComparisonOfValuationPerformance_peKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析-市盈率拆分表.securCode
     *
     * @mbggenerated
     */
    private String securcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析-市盈率拆分表.computMothd
     *
     * @mbggenerated
     */
    private String computmothd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析-市盈率拆分表.securCode
     *
     * @return the value of 估值表现分析-市盈率拆分表.securCode
     *
     * @mbggenerated
     */
    public String getSecurcode() {
        return securcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析-市盈率拆分表.securCode
     *
     * @param securcode the value for 估值表现分析-市盈率拆分表.securCode
     *
     * @mbggenerated
     */
    public void setSecurcode(String securcode) {
        this.securcode = securcode == null ? null : securcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析-市盈率拆分表.computMothd
     *
     * @return the value of 估值表现分析-市盈率拆分表.computMothd
     *
     * @mbggenerated
     */
    public String getComputmothd() {
        return computmothd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析-市盈率拆分表.computMothd
     *
     * @param computmothd the value for 估值表现分析-市盈率拆分表.computMothd
     *
     * @mbggenerated
     */
    public void setComputmothd(String computmothd) {
        this.computmothd = computmothd == null ? null : computmothd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfValuationPerformance_peKey other = (ComparisonOfValuationPerformance_peKey) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getComputmothd() == null ? other.getComputmothd() == null : this.getComputmothd().equals(other.getComputmothd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getComputmothd() == null) ? 0 : getComputmothd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", securcode=").append(securcode);
        sb.append(", computmothd=").append(computmothd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}