package com.citicup.model;

import java.io.Serializable;

public class ComparisonOfMarketPerformance_risefal implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.securCode
     *
     * @mbggenerated
     */
    private String securcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.new
     *
     * @mbggenerated
     */
    private String new;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.thWk
     *
     * @mbggenerated
     */
    private String thwk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.thMth
     *
     * @mbggenerated
     */
    private String thmth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.thYear
     *
     * @mbggenerated
     */
    private String thyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.nearAMth
     *
     * @mbggenerated
     */
    private String nearamth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.nearThrMth
     *
     * @mbggenerated
     */
    private String nearthrmth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.nearSixMth
     *
     * @mbggenerated
     */
    private String nearsixmth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现比较-risefal.nearAYear
     *
     * @mbggenerated
     */
    private String nearayear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 市场表现比较-risefal
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.securCode
     *
     * @return the value of 市场表现比较-risefal.securCode
     *
     * @mbggenerated
     */
    public String getSecurcode() {
        return securcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.securCode
     *
     * @param securcode the value for 市场表现比较-risefal.securCode
     *
     * @mbggenerated
     */
    public void setSecurcode(String securcode) {
        this.securcode = securcode == null ? null : securcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.new
     *
     * @return the value of 市场表现比较-risefal.new
     *
     * @mbggenerated
     */
    public String getNew() {
        return new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.new
     *
     * @param new the value for 市场表现比较-risefal.new
     *
     * @mbggenerated
     */
    public void setNew(String new) {
        this.new = new == null ? null : new.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.thWk
     *
     * @return the value of 市场表现比较-risefal.thWk
     *
     * @mbggenerated
     */
    public String getThwk() {
        return thwk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.thWk
     *
     * @param thwk the value for 市场表现比较-risefal.thWk
     *
     * @mbggenerated
     */
    public void setThwk(String thwk) {
        this.thwk = thwk == null ? null : thwk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.thMth
     *
     * @return the value of 市场表现比较-risefal.thMth
     *
     * @mbggenerated
     */
    public String getThmth() {
        return thmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.thMth
     *
     * @param thmth the value for 市场表现比较-risefal.thMth
     *
     * @mbggenerated
     */
    public void setThmth(String thmth) {
        this.thmth = thmth == null ? null : thmth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.thYear
     *
     * @return the value of 市场表现比较-risefal.thYear
     *
     * @mbggenerated
     */
    public String getThyear() {
        return thyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.thYear
     *
     * @param thyear the value for 市场表现比较-risefal.thYear
     *
     * @mbggenerated
     */
    public void setThyear(String thyear) {
        this.thyear = thyear == null ? null : thyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.nearAMth
     *
     * @return the value of 市场表现比较-risefal.nearAMth
     *
     * @mbggenerated
     */
    public String getNearamth() {
        return nearamth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.nearAMth
     *
     * @param nearamth the value for 市场表现比较-risefal.nearAMth
     *
     * @mbggenerated
     */
    public void setNearamth(String nearamth) {
        this.nearamth = nearamth == null ? null : nearamth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.nearThrMth
     *
     * @return the value of 市场表现比较-risefal.nearThrMth
     *
     * @mbggenerated
     */
    public String getNearthrmth() {
        return nearthrmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.nearThrMth
     *
     * @param nearthrmth the value for 市场表现比较-risefal.nearThrMth
     *
     * @mbggenerated
     */
    public void setNearthrmth(String nearthrmth) {
        this.nearthrmth = nearthrmth == null ? null : nearthrmth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.nearSixMth
     *
     * @return the value of 市场表现比较-risefal.nearSixMth
     *
     * @mbggenerated
     */
    public String getNearsixmth() {
        return nearsixmth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.nearSixMth
     *
     * @param nearsixmth the value for 市场表现比较-risefal.nearSixMth
     *
     * @mbggenerated
     */
    public void setNearsixmth(String nearsixmth) {
        this.nearsixmth = nearsixmth == null ? null : nearsixmth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现比较-risefal.nearAYear
     *
     * @return the value of 市场表现比较-risefal.nearAYear
     *
     * @mbggenerated
     */
    public String getNearayear() {
        return nearayear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现比较-risefal.nearAYear
     *
     * @param nearayear the value for 市场表现比较-risefal.nearAYear
     *
     * @mbggenerated
     */
    public void setNearayear(String nearayear) {
        this.nearayear = nearayear == null ? null : nearayear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现比较-risefal
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfMarketPerformance_risefal other = (ComparisonOfMarketPerformance_risefal) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getNew() == null ? other.getNew() == null : this.getNew().equals(other.getNew()))
            && (this.getThwk() == null ? other.getThwk() == null : this.getThwk().equals(other.getThwk()))
            && (this.getThmth() == null ? other.getThmth() == null : this.getThmth().equals(other.getThmth()))
            && (this.getThyear() == null ? other.getThyear() == null : this.getThyear().equals(other.getThyear()))
            && (this.getNearamth() == null ? other.getNearamth() == null : this.getNearamth().equals(other.getNearamth()))
            && (this.getNearthrmth() == null ? other.getNearthrmth() == null : this.getNearthrmth().equals(other.getNearthrmth()))
            && (this.getNearsixmth() == null ? other.getNearsixmth() == null : this.getNearsixmth().equals(other.getNearsixmth()))
            && (this.getNearayear() == null ? other.getNearayear() == null : this.getNearayear().equals(other.getNearayear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现比较-risefal
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getNew() == null) ? 0 : getNew().hashCode());
        result = prime * result + ((getThwk() == null) ? 0 : getThwk().hashCode());
        result = prime * result + ((getThmth() == null) ? 0 : getThmth().hashCode());
        result = prime * result + ((getThyear() == null) ? 0 : getThyear().hashCode());
        result = prime * result + ((getNearamth() == null) ? 0 : getNearamth().hashCode());
        result = prime * result + ((getNearthrmth() == null) ? 0 : getNearthrmth().hashCode());
        result = prime * result + ((getNearsixmth() == null) ? 0 : getNearsixmth().hashCode());
        result = prime * result + ((getNearayear() == null) ? 0 : getNearayear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现比较-risefal
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", securcode=").append(securcode);
        sb.append(", new=").append(new);
        sb.append(", thwk=").append(thwk);
        sb.append(", thmth=").append(thmth);
        sb.append(", thyear=").append(thyear);
        sb.append(", nearamth=").append(nearamth);
        sb.append(", nearthrmth=").append(nearthrmth);
        sb.append(", nearsixmth=").append(nearsixmth);
        sb.append(", nearayear=").append(nearayear);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}