package com.citicup.model;

import java.io.Serializable;

public class ComparisonOfValuationPerformance_pe extends ComparisonOfValuationPerformance_peKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析-市盈率拆分表.PETTM
     *
     * @mbggenerated
     */
    private String pettm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析-市盈率拆分表.PETTM
     *
     * @return the value of 估值表现分析-市盈率拆分表.PETTM
     *
     * @mbggenerated
     */
    public String getPettm() {
        return pettm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析-市盈率拆分表.PETTM
     *
     * @param pettm the value for 估值表现分析-市盈率拆分表.PETTM
     *
     * @mbggenerated
     */
    public void setPettm(String pettm) {
        this.pettm = pettm == null ? null : pettm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfValuationPerformance_pe other = (ComparisonOfValuationPerformance_pe) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getComputmothd() == null ? other.getComputmothd() == null : this.getComputmothd().equals(other.getComputmothd()))
            && (this.getPettm() == null ? other.getPettm() == null : this.getPettm().equals(other.getPettm()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getComputmothd() == null) ? 0 : getComputmothd().hashCode());
        result = prime * result + ((getPettm() == null) ? 0 : getPettm().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-市盈率拆分表
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pettm=").append(pettm);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}