package com.citicup.model;

import java.io.Serializable;

public class EquityTurnover extends EquityTurnoverKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 股东权益周转率.equityTurn
     *
     * @mbggenerated
     */
    private String equityturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 股东权益周转率.equityTurn
     *
     * @return the value of 股东权益周转率.equityTurn
     *
     * @mbggenerated
     */
    public String getEquityturn() {
        return equityturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 股东权益周转率.equityTurn
     *
     * @param equityturn the value for 股东权益周转率.equityTurn
     *
     * @mbggenerated
     */
    public void setEquityturn(String equityturn) {
        this.equityturn = equityturn == null ? null : equityturn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EquityTurnover other = (EquityTurnover) that;
        return (this.get﻿stkcd() == null ? other.get﻿stkcd() == null : this.get﻿stkcd().equals(other.get﻿stkcd()))
            && (this.getAcceper() == null ? other.getAcceper() == null : this.getAcceper().equals(other.getAcceper()))
            && (this.getEquityturn() == null ? other.getEquityturn() == null : this.getEquityturn().equals(other.getEquityturn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((get﻿stkcd() == null) ? 0 : get﻿stkcd().hashCode());
        result = prime * result + ((getAcceper() == null) ? 0 : getAcceper().hashCode());
        result = prime * result + ((getEquityturn() == null) ? 0 : getEquityturn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", equityturn=").append(equityturn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}