package com.citicup.model;

import java.io.Serializable;

public class FixedAssetsInvestmentOfAutoIndustryInChina implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.automobile
     *
     * @mbggenerated
     */
    private String automobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.modCar
     *
     * @mbggenerated
     */
    private String modcar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.motorcycle
     *
     * @mbggenerated
     */
    private String motorcycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.vehicleEng
     *
     * @mbggenerated
     */
    private String vehicleeng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.autoAndMoto
     *
     * @mbggenerated
     */
    private String autoandmoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国汽车行业固定资产投资额.totalAuto
     *
     * @mbggenerated
     */
    private String totalauto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国汽车行业固定资产投资额
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.year
     *
     * @return the value of 中国汽车行业固定资产投资额.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.year
     *
     * @param year the value for 中国汽车行业固定资产投资额.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.automobile
     *
     * @return the value of 中国汽车行业固定资产投资额.automobile
     *
     * @mbggenerated
     */
    public String getAutomobile() {
        return automobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.automobile
     *
     * @param automobile the value for 中国汽车行业固定资产投资额.automobile
     *
     * @mbggenerated
     */
    public void setAutomobile(String automobile) {
        this.automobile = automobile == null ? null : automobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.modCar
     *
     * @return the value of 中国汽车行业固定资产投资额.modCar
     *
     * @mbggenerated
     */
    public String getModcar() {
        return modcar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.modCar
     *
     * @param modcar the value for 中国汽车行业固定资产投资额.modCar
     *
     * @mbggenerated
     */
    public void setModcar(String modcar) {
        this.modcar = modcar == null ? null : modcar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.motorcycle
     *
     * @return the value of 中国汽车行业固定资产投资额.motorcycle
     *
     * @mbggenerated
     */
    public String getMotorcycle() {
        return motorcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.motorcycle
     *
     * @param motorcycle the value for 中国汽车行业固定资产投资额.motorcycle
     *
     * @mbggenerated
     */
    public void setMotorcycle(String motorcycle) {
        this.motorcycle = motorcycle == null ? null : motorcycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.vehicleEng
     *
     * @return the value of 中国汽车行业固定资产投资额.vehicleEng
     *
     * @mbggenerated
     */
    public String getVehicleeng() {
        return vehicleeng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.vehicleEng
     *
     * @param vehicleeng the value for 中国汽车行业固定资产投资额.vehicleEng
     *
     * @mbggenerated
     */
    public void setVehicleeng(String vehicleeng) {
        this.vehicleeng = vehicleeng == null ? null : vehicleeng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.autoAndMoto
     *
     * @return the value of 中国汽车行业固定资产投资额.autoAndMoto
     *
     * @mbggenerated
     */
    public String getAutoandmoto() {
        return autoandmoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.autoAndMoto
     *
     * @param autoandmoto the value for 中国汽车行业固定资产投资额.autoAndMoto
     *
     * @mbggenerated
     */
    public void setAutoandmoto(String autoandmoto) {
        this.autoandmoto = autoandmoto == null ? null : autoandmoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国汽车行业固定资产投资额.totalAuto
     *
     * @return the value of 中国汽车行业固定资产投资额.totalAuto
     *
     * @mbggenerated
     */
    public String getTotalauto() {
        return totalauto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国汽车行业固定资产投资额.totalAuto
     *
     * @param totalauto the value for 中国汽车行业固定资产投资额.totalAuto
     *
     * @mbggenerated
     */
    public void setTotalauto(String totalauto) {
        this.totalauto = totalauto == null ? null : totalauto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业固定资产投资额
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FixedAssetsInvestmentOfAutoIndustryInChina other = (FixedAssetsInvestmentOfAutoIndustryInChina) that;
        return (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getAutomobile() == null ? other.getAutomobile() == null : this.getAutomobile().equals(other.getAutomobile()))
            && (this.getModcar() == null ? other.getModcar() == null : this.getModcar().equals(other.getModcar()))
            && (this.getMotorcycle() == null ? other.getMotorcycle() == null : this.getMotorcycle().equals(other.getMotorcycle()))
            && (this.getVehicleeng() == null ? other.getVehicleeng() == null : this.getVehicleeng().equals(other.getVehicleeng()))
            && (this.getAutoandmoto() == null ? other.getAutoandmoto() == null : this.getAutoandmoto().equals(other.getAutoandmoto()))
            && (this.getTotalauto() == null ? other.getTotalauto() == null : this.getTotalauto().equals(other.getTotalauto()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业固定资产投资额
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getAutomobile() == null) ? 0 : getAutomobile().hashCode());
        result = prime * result + ((getModcar() == null) ? 0 : getModcar().hashCode());
        result = prime * result + ((getMotorcycle() == null) ? 0 : getMotorcycle().hashCode());
        result = prime * result + ((getVehicleeng() == null) ? 0 : getVehicleeng().hashCode());
        result = prime * result + ((getAutoandmoto() == null) ? 0 : getAutoandmoto().hashCode());
        result = prime * result + ((getTotalauto() == null) ? 0 : getTotalauto().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业固定资产投资额
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", year=").append(year);
        sb.append(", automobile=").append(automobile);
        sb.append(", modcar=").append(modcar);
        sb.append(", motorcycle=").append(motorcycle);
        sb.append(", vehicleeng=").append(vehicleeng);
        sb.append(", autoandmoto=").append(autoandmoto);
        sb.append(", totalauto=").append(totalauto);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}