package com.citicup.model;

import java.io.Serializable;

public class NetProfitGrowthRate extends NetProfitGrowthRateKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 净利润增长率.netProGrowthRate
     *
     * @mbggenerated
     */
    private String netprogrowthrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 净利润增长率.netProGrowthRate
     *
     * @return the value of 净利润增长率.netProGrowthRate
     *
     * @mbggenerated
     */
    public String getNetprogrowthrate() {
        return netprogrowthrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 净利润增长率.netProGrowthRate
     *
     * @param netprogrowthrate the value for 净利润增长率.netProGrowthRate
     *
     * @mbggenerated
     */
    public void setNetprogrowthrate(String netprogrowthrate) {
        this.netprogrowthrate = netprogrowthrate == null ? null : netprogrowthrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NetProfitGrowthRate other = (NetProfitGrowthRate) that;
        return (this.get﻿stkcd() == null ? other.get﻿stkcd() == null : this.get﻿stkcd().equals(other.get﻿stkcd()))
            && (this.getFiscalyear() == null ? other.getFiscalyear() == null : this.getFiscalyear().equals(other.getFiscalyear()))
            && (this.getNetprogrowthrate() == null ? other.getNetprogrowthrate() == null : this.getNetprogrowthrate().equals(other.getNetprogrowthrate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((get﻿stkcd() == null) ? 0 : get﻿stkcd().hashCode());
        result = prime * result + ((getFiscalyear() == null) ? 0 : getFiscalyear().hashCode());
        result = prime * result + ((getNetprogrowthrate() == null) ? 0 : getNetprogrowthrate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", netprogrowthrate=").append(netprogrowthrate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}