package com.citicup.model;

import java.io.Serializable;

public class PointKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.stkcd
     *
     * @mbggenerated
     */
    private String stkcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.graphId
     *
     * @mbggenerated
     */
    private String graphid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table point
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.stkcd
     *
     * @return the value of point.stkcd
     *
     * @mbggenerated
     */
    public String getStkcd() {
        return stkcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.stkcd
     *
     * @param stkcd the value for point.stkcd
     *
     * @mbggenerated
     */
    public void setStkcd(String stkcd) {
        this.stkcd = stkcd == null ? null : stkcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.graphId
     *
     * @return the value of point.graphId
     *
     * @mbggenerated
     */
    public String getGraphid() {
        return graphid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.graphId
     *
     * @param graphid the value for point.graphId
     *
     * @mbggenerated
     */
    public void setGraphid(String graphid) {
        this.graphid = graphid == null ? null : graphid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PointKey other = (PointKey) that;
        return (this.getStkcd() == null ? other.getStkcd() == null : this.getStkcd().equals(other.getStkcd()))
            && (this.getGraphid() == null ? other.getGraphid() == null : this.getGraphid().equals(other.getGraphid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStkcd() == null) ? 0 : getStkcd().hashCode());
        result = prime * result + ((getGraphid() == null) ? 0 : getGraphid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stkcd=").append(stkcd);
        sb.append(", graphid=").append(graphid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public PointKey(String stkcd, String graphid) {
        this.stkcd = stkcd;
        this.graphid = graphid;
    }

    public PointKey() {
    }
}