package com.citicup.model;

import java.io.Serializable;

public class RateOfReturnOnInvestment extends RateOfReturnOnInvestmentKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 投资收益率.returnOnInvest
     *
     * @mbggenerated
     */
    private String returnoninvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 投资收益率.returnOnInvest
     *
     * @return the value of 投资收益率.returnOnInvest
     *
     * @mbggenerated
     */
    public String getReturnoninvest() {
        return returnoninvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 投资收益率.returnOnInvest
     *
     * @param returnoninvest the value for 投资收益率.returnOnInvest
     *
     * @mbggenerated
     */
    public void setReturnoninvest(String returnoninvest) {
        this.returnoninvest = returnoninvest == null ? null : returnoninvest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RateOfReturnOnInvestment other = (RateOfReturnOnInvestment) that;
        return (this.get﻿stkcd() == null ? other.get﻿stkcd() == null : this.get﻿stkcd().equals(other.get﻿stkcd()))
            && (this.getAcceper() == null ? other.getAcceper() == null : this.getAcceper().equals(other.getAcceper()))
            && (this.getReturnoninvest() == null ? other.getReturnoninvest() == null : this.getReturnoninvest().equals(other.getReturnoninvest()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((get﻿stkcd() == null) ? 0 : get﻿stkcd().hashCode());
        result = prime * result + ((getAcceper() == null) ? 0 : getAcceper().hashCode());
        result = prime * result + ((getReturnoninvest() == null) ? 0 : getReturnoninvest().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", returnoninvest=").append(returnoninvest);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}