package com.citicup.model.peValuation;

import java.io.Serializable;

public class PE_historyKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pe_history.TradingDate
     *
     * @mbggenerated
     */
    private String tradingdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pe_history.Symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pe_history.TradingDate
     *
     * @return the value of pe_history.TradingDate
     *
     * @mbggenerated
     */
    public String getTradingdate() {
        return tradingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pe_history.TradingDate
     *
     * @param tradingdate the value for pe_history.TradingDate
     *
     * @mbggenerated
     */
    public void setTradingdate(String tradingdate) {
        this.tradingdate = tradingdate == null ? null : tradingdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pe_history.Symbol
     *
     * @return the value of pe_history.Symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pe_history.Symbol
     *
     * @param symbol the value for pe_history.Symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PE_historyKey other = (PE_historyKey) that;
        return (this.getTradingdate() == null ? other.getTradingdate() == null : this.getTradingdate().equals(other.getTradingdate()))
            && (this.getSymbol() == null ? other.getSymbol() == null : this.getSymbol().equals(other.getSymbol()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTradingdate() == null) ? 0 : getTradingdate().hashCode());
        result = prime * result + ((getSymbol() == null) ? 0 : getSymbol().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tradingdate=").append(tradingdate);
        sb.append(", symbol=").append(symbol);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}