package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class AutomobileIndustryBulletinInformation extends AutomobileIndustryBulletinInformationKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 汽车行业公告信息.summaryContent
     *
     * @mbggenerated
     */
    private String summarycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 汽车行业公告信息.summaryContent
     *
     * @return the value of 汽车行业公告信息.summaryContent
     *
     * @mbggenerated
     */
    public String getSummarycontent() {
        return summarycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 汽车行业公告信息.summaryContent
     *
     * @param summarycontent the value for 汽车行业公告信息.summaryContent
     *
     * @mbggenerated
     */
    public void setSummarycontent(String summarycontent) {
        this.summarycontent = summarycontent == null ? null : summarycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AutomobileIndustryBulletinInformation other = (AutomobileIndustryBulletinInformation) that;
        return (this.getDeclaredate() == null ? other.getDeclaredate() == null : this.getDeclaredate().equals(other.getDeclaredate()))
            && (this.getSummarytitle() == null ? other.getSummarytitle() == null : this.getSummarytitle().equals(other.getSummarytitle()))
            && (this.getSummarycontent() == null ? other.getSummarycontent() == null : this.getSummarycontent().equals(other.getSummarycontent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDeclaredate() == null) ? 0 : getDeclaredate().hashCode());
        result = prime * result + ((getSummarytitle() == null) ? 0 : getSummarytitle().hashCode());
        result = prime * result + ((getSummarycontent() == null) ? 0 : getSummarycontent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", summarycontent=").append(summarycontent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}