package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ChineseDomesticManufacturingPassengerCarProductionDividedByType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国国内制造乘用车分车型产量.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国国内制造乘用车分车型产量.basicProductionMICHN
     *
     * @mbggenerated
     */
    private String basicproductionmichn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国国内制造乘用车分车型产量.MPVProductionMICHN
     *
     * @mbggenerated
     */
    private String mpvproductionmichn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国国内制造乘用车分车型产量.SUVProductionMICHN
     *
     * @mbggenerated
     */
    private String suvproductionmichn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 中国国内制造乘用车分车型产量.acrossProductionMICHN
     *
     * @mbggenerated
     */
    private String acrossproductionmichn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 中国国内制造乘用车分车型产量
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国国内制造乘用车分车型产量.f1
     *
     * @return the value of 中国国内制造乘用车分车型产量.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国国内制造乘用车分车型产量.f1
     *
     * @param f1 the value for 中国国内制造乘用车分车型产量.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国国内制造乘用车分车型产量.basicProductionMICHN
     *
     * @return the value of 中国国内制造乘用车分车型产量.basicProductionMICHN
     *
     * @mbggenerated
     */
    public String getBasicproductionmichn() {
        return basicproductionmichn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国国内制造乘用车分车型产量.basicProductionMICHN
     *
     * @param basicproductionmichn the value for 中国国内制造乘用车分车型产量.basicProductionMICHN
     *
     * @mbggenerated
     */
    public void setBasicproductionmichn(String basicproductionmichn) {
        this.basicproductionmichn = basicproductionmichn == null ? null : basicproductionmichn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国国内制造乘用车分车型产量.MPVProductionMICHN
     *
     * @return the value of 中国国内制造乘用车分车型产量.MPVProductionMICHN
     *
     * @mbggenerated
     */
    public String getMpvproductionmichn() {
        return mpvproductionmichn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国国内制造乘用车分车型产量.MPVProductionMICHN
     *
     * @param mpvproductionmichn the value for 中国国内制造乘用车分车型产量.MPVProductionMICHN
     *
     * @mbggenerated
     */
    public void setMpvproductionmichn(String mpvproductionmichn) {
        this.mpvproductionmichn = mpvproductionmichn == null ? null : mpvproductionmichn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国国内制造乘用车分车型产量.SUVProductionMICHN
     *
     * @return the value of 中国国内制造乘用车分车型产量.SUVProductionMICHN
     *
     * @mbggenerated
     */
    public String getSuvproductionmichn() {
        return suvproductionmichn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国国内制造乘用车分车型产量.SUVProductionMICHN
     *
     * @param suvproductionmichn the value for 中国国内制造乘用车分车型产量.SUVProductionMICHN
     *
     * @mbggenerated
     */
    public void setSuvproductionmichn(String suvproductionmichn) {
        this.suvproductionmichn = suvproductionmichn == null ? null : suvproductionmichn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 中国国内制造乘用车分车型产量.acrossProductionMICHN
     *
     * @return the value of 中国国内制造乘用车分车型产量.acrossProductionMICHN
     *
     * @mbggenerated
     */
    public String getAcrossproductionmichn() {
        return acrossproductionmichn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 中国国内制造乘用车分车型产量.acrossProductionMICHN
     *
     * @param acrossproductionmichn the value for 中国国内制造乘用车分车型产量.acrossProductionMICHN
     *
     * @mbggenerated
     */
    public void setAcrossproductionmichn(String acrossproductionmichn) {
        this.acrossproductionmichn = acrossproductionmichn == null ? null : acrossproductionmichn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型产量
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ChineseDomesticManufacturingPassengerCarProductionDividedByType other = (ChineseDomesticManufacturingPassengerCarProductionDividedByType) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getBasicproductionmichn() == null ? other.getBasicproductionmichn() == null : this.getBasicproductionmichn().equals(other.getBasicproductionmichn()))
            && (this.getMpvproductionmichn() == null ? other.getMpvproductionmichn() == null : this.getMpvproductionmichn().equals(other.getMpvproductionmichn()))
            && (this.getSuvproductionmichn() == null ? other.getSuvproductionmichn() == null : this.getSuvproductionmichn().equals(other.getSuvproductionmichn()))
            && (this.getAcrossproductionmichn() == null ? other.getAcrossproductionmichn() == null : this.getAcrossproductionmichn().equals(other.getAcrossproductionmichn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型产量
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getBasicproductionmichn() == null) ? 0 : getBasicproductionmichn().hashCode());
        result = prime * result + ((getMpvproductionmichn() == null) ? 0 : getMpvproductionmichn().hashCode());
        result = prime * result + ((getSuvproductionmichn() == null) ? 0 : getSuvproductionmichn().hashCode());
        result = prime * result + ((getAcrossproductionmichn() == null) ? 0 : getAcrossproductionmichn().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型产量
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", basicproductionmichn=").append(basicproductionmichn);
        sb.append(", mpvproductionmichn=").append(mpvproductionmichn);
        sb.append(", suvproductionmichn=").append(suvproductionmichn);
        sb.append(", acrossproductionmichn=").append(acrossproductionmichn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}