package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ComparisonOfFinancialData_splitTable extends ComparisonOfFinancialData_splitTableKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toInc
     *
     * @mbggenerated
     */
    private String toinc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toIncYoyGrowRate
     *
     * @mbggenerated
     */
    private String toincyoygrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netPro
     *
     * @mbggenerated
     */
    private String netpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netProYoyGrowRate
     *
     * @mbggenerated
     */
    private String netproyoygrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.EBIT
     *
     * @mbggenerated
     */
    private String ebit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.EBITDA
     *
     * @mbggenerated
     */
    private String ebitda;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toAsst
     *
     * @mbggenerated
     */
    private String toasst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toAsstYoyGrowRate
     *
     * @mbggenerated
     */
    private String toasstyoygrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toLiablt
     *
     * @mbggenerated
     */
    private String toliablt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.toLiabltYoyGrowRate
     *
     * @mbggenerated
     */
    private String toliabltyoygrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.sharehldRigInt
     *
     * @mbggenerated
     */
    private String sharehldrigint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.sharehldRigIntYoyGrowRate
     *
     * @mbggenerated
     */
    private String sharehldrigintyoygrowrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netCshFlow
     *
     * @mbggenerated
     */
    private String netcshflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netCshFlOperAct
     *
     * @mbggenerated
     */
    private String netcshfloperact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netCshFlInvAct
     *
     * @mbggenerated
     */
    private String netcshflinvact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.netCshFlFinAct
     *
     * @mbggenerated
     */
    private String netcshflfinact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toInc
     *
     * @return the value of 财务数据比较-拆分表.toInc
     *
     * @mbggenerated
     */
    public String getToinc() {
        return toinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toInc
     *
     * @param toinc the value for 财务数据比较-拆分表.toInc
     *
     * @mbggenerated
     */
    public void setToinc(String toinc) {
        this.toinc = toinc == null ? null : toinc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toIncYoyGrowRate
     *
     * @return the value of 财务数据比较-拆分表.toIncYoyGrowRate
     *
     * @mbggenerated
     */
    public String getToincyoygrowrate() {
        return toincyoygrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toIncYoyGrowRate
     *
     * @param toincyoygrowrate the value for 财务数据比较-拆分表.toIncYoyGrowRate
     *
     * @mbggenerated
     */
    public void setToincyoygrowrate(String toincyoygrowrate) {
        this.toincyoygrowrate = toincyoygrowrate == null ? null : toincyoygrowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netPro
     *
     * @return the value of 财务数据比较-拆分表.netPro
     *
     * @mbggenerated
     */
    public String getNetpro() {
        return netpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netPro
     *
     * @param netpro the value for 财务数据比较-拆分表.netPro
     *
     * @mbggenerated
     */
    public void setNetpro(String netpro) {
        this.netpro = netpro == null ? null : netpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netProYoyGrowRate
     *
     * @return the value of 财务数据比较-拆分表.netProYoyGrowRate
     *
     * @mbggenerated
     */
    public String getNetproyoygrowrate() {
        return netproyoygrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netProYoyGrowRate
     *
     * @param netproyoygrowrate the value for 财务数据比较-拆分表.netProYoyGrowRate
     *
     * @mbggenerated
     */
    public void setNetproyoygrowrate(String netproyoygrowrate) {
        this.netproyoygrowrate = netproyoygrowrate == null ? null : netproyoygrowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.EBIT
     *
     * @return the value of 财务数据比较-拆分表.EBIT
     *
     * @mbggenerated
     */
    public String getEbit() {
        return ebit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.EBIT
     *
     * @param ebit the value for 财务数据比较-拆分表.EBIT
     *
     * @mbggenerated
     */
    public void setEbit(String ebit) {
        this.ebit = ebit == null ? null : ebit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.EBITDA
     *
     * @return the value of 财务数据比较-拆分表.EBITDA
     *
     * @mbggenerated
     */
    public String getEbitda() {
        return ebitda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.EBITDA
     *
     * @param ebitda the value for 财务数据比较-拆分表.EBITDA
     *
     * @mbggenerated
     */
    public void setEbitda(String ebitda) {
        this.ebitda = ebitda == null ? null : ebitda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toAsst
     *
     * @return the value of 财务数据比较-拆分表.toAsst
     *
     * @mbggenerated
     */
    public String getToasst() {
        return toasst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toAsst
     *
     * @param toasst the value for 财务数据比较-拆分表.toAsst
     *
     * @mbggenerated
     */
    public void setToasst(String toasst) {
        this.toasst = toasst == null ? null : toasst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toAsstYoyGrowRate
     *
     * @return the value of 财务数据比较-拆分表.toAsstYoyGrowRate
     *
     * @mbggenerated
     */
    public String getToasstyoygrowrate() {
        return toasstyoygrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toAsstYoyGrowRate
     *
     * @param toasstyoygrowrate the value for 财务数据比较-拆分表.toAsstYoyGrowRate
     *
     * @mbggenerated
     */
    public void setToasstyoygrowrate(String toasstyoygrowrate) {
        this.toasstyoygrowrate = toasstyoygrowrate == null ? null : toasstyoygrowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toLiablt
     *
     * @return the value of 财务数据比较-拆分表.toLiablt
     *
     * @mbggenerated
     */
    public String getToliablt() {
        return toliablt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toLiablt
     *
     * @param toliablt the value for 财务数据比较-拆分表.toLiablt
     *
     * @mbggenerated
     */
    public void setToliablt(String toliablt) {
        this.toliablt = toliablt == null ? null : toliablt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.toLiabltYoyGrowRate
     *
     * @return the value of 财务数据比较-拆分表.toLiabltYoyGrowRate
     *
     * @mbggenerated
     */
    public String getToliabltyoygrowrate() {
        return toliabltyoygrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.toLiabltYoyGrowRate
     *
     * @param toliabltyoygrowrate the value for 财务数据比较-拆分表.toLiabltYoyGrowRate
     *
     * @mbggenerated
     */
    public void setToliabltyoygrowrate(String toliabltyoygrowrate) {
        this.toliabltyoygrowrate = toliabltyoygrowrate == null ? null : toliabltyoygrowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.sharehldRigInt
     *
     * @return the value of 财务数据比较-拆分表.sharehldRigInt
     *
     * @mbggenerated
     */
    public String getSharehldrigint() {
        return sharehldrigint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.sharehldRigInt
     *
     * @param sharehldrigint the value for 财务数据比较-拆分表.sharehldRigInt
     *
     * @mbggenerated
     */
    public void setSharehldrigint(String sharehldrigint) {
        this.sharehldrigint = sharehldrigint == null ? null : sharehldrigint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.sharehldRigIntYoyGrowRate
     *
     * @return the value of 财务数据比较-拆分表.sharehldRigIntYoyGrowRate
     *
     * @mbggenerated
     */
    public String getSharehldrigintyoygrowrate() {
        return sharehldrigintyoygrowrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.sharehldRigIntYoyGrowRate
     *
     * @param sharehldrigintyoygrowrate the value for 财务数据比较-拆分表.sharehldRigIntYoyGrowRate
     *
     * @mbggenerated
     */
    public void setSharehldrigintyoygrowrate(String sharehldrigintyoygrowrate) {
        this.sharehldrigintyoygrowrate = sharehldrigintyoygrowrate == null ? null : sharehldrigintyoygrowrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netCshFlow
     *
     * @return the value of 财务数据比较-拆分表.netCshFlow
     *
     * @mbggenerated
     */
    public String getNetcshflow() {
        return netcshflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netCshFlow
     *
     * @param netcshflow the value for 财务数据比较-拆分表.netCshFlow
     *
     * @mbggenerated
     */
    public void setNetcshflow(String netcshflow) {
        this.netcshflow = netcshflow == null ? null : netcshflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netCshFlOperAct
     *
     * @return the value of 财务数据比较-拆分表.netCshFlOperAct
     *
     * @mbggenerated
     */
    public String getNetcshfloperact() {
        return netcshfloperact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netCshFlOperAct
     *
     * @param netcshfloperact the value for 财务数据比较-拆分表.netCshFlOperAct
     *
     * @mbggenerated
     */
    public void setNetcshfloperact(String netcshfloperact) {
        this.netcshfloperact = netcshfloperact == null ? null : netcshfloperact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netCshFlInvAct
     *
     * @return the value of 财务数据比较-拆分表.netCshFlInvAct
     *
     * @mbggenerated
     */
    public String getNetcshflinvact() {
        return netcshflinvact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netCshFlInvAct
     *
     * @param netcshflinvact the value for 财务数据比较-拆分表.netCshFlInvAct
     *
     * @mbggenerated
     */
    public void setNetcshflinvact(String netcshflinvact) {
        this.netcshflinvact = netcshflinvact == null ? null : netcshflinvact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.netCshFlFinAct
     *
     * @return the value of 财务数据比较-拆分表.netCshFlFinAct
     *
     * @mbggenerated
     */
    public String getNetcshflfinact() {
        return netcshflfinact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.netCshFlFinAct
     *
     * @param netcshflfinact the value for 财务数据比较-拆分表.netCshFlFinAct
     *
     * @mbggenerated
     */
    public void setNetcshflfinact(String netcshflfinact) {
        this.netcshflfinact = netcshflfinact == null ? null : netcshflfinact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfFinancialData_splitTable other = (ComparisonOfFinancialData_splitTable) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getToinc() == null ? other.getToinc() == null : this.getToinc().equals(other.getToinc()))
            && (this.getToincyoygrowrate() == null ? other.getToincyoygrowrate() == null : this.getToincyoygrowrate().equals(other.getToincyoygrowrate()))
            && (this.getNetpro() == null ? other.getNetpro() == null : this.getNetpro().equals(other.getNetpro()))
            && (this.getNetproyoygrowrate() == null ? other.getNetproyoygrowrate() == null : this.getNetproyoygrowrate().equals(other.getNetproyoygrowrate()))
            && (this.getEbit() == null ? other.getEbit() == null : this.getEbit().equals(other.getEbit()))
            && (this.getEbitda() == null ? other.getEbitda() == null : this.getEbitda().equals(other.getEbitda()))
            && (this.getToasst() == null ? other.getToasst() == null : this.getToasst().equals(other.getToasst()))
            && (this.getToasstyoygrowrate() == null ? other.getToasstyoygrowrate() == null : this.getToasstyoygrowrate().equals(other.getToasstyoygrowrate()))
            && (this.getToliablt() == null ? other.getToliablt() == null : this.getToliablt().equals(other.getToliablt()))
            && (this.getToliabltyoygrowrate() == null ? other.getToliabltyoygrowrate() == null : this.getToliabltyoygrowrate().equals(other.getToliabltyoygrowrate()))
            && (this.getSharehldrigint() == null ? other.getSharehldrigint() == null : this.getSharehldrigint().equals(other.getSharehldrigint()))
            && (this.getSharehldrigintyoygrowrate() == null ? other.getSharehldrigintyoygrowrate() == null : this.getSharehldrigintyoygrowrate().equals(other.getSharehldrigintyoygrowrate()))
            && (this.getNetcshflow() == null ? other.getNetcshflow() == null : this.getNetcshflow().equals(other.getNetcshflow()))
            && (this.getNetcshfloperact() == null ? other.getNetcshfloperact() == null : this.getNetcshfloperact().equals(other.getNetcshfloperact()))
            && (this.getNetcshflinvact() == null ? other.getNetcshflinvact() == null : this.getNetcshflinvact().equals(other.getNetcshflinvact()))
            && (this.getNetcshflfinact() == null ? other.getNetcshflfinact() == null : this.getNetcshflfinact().equals(other.getNetcshflfinact()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getToinc() == null) ? 0 : getToinc().hashCode());
        result = prime * result + ((getToincyoygrowrate() == null) ? 0 : getToincyoygrowrate().hashCode());
        result = prime * result + ((getNetpro() == null) ? 0 : getNetpro().hashCode());
        result = prime * result + ((getNetproyoygrowrate() == null) ? 0 : getNetproyoygrowrate().hashCode());
        result = prime * result + ((getEbit() == null) ? 0 : getEbit().hashCode());
        result = prime * result + ((getEbitda() == null) ? 0 : getEbitda().hashCode());
        result = prime * result + ((getToasst() == null) ? 0 : getToasst().hashCode());
        result = prime * result + ((getToasstyoygrowrate() == null) ? 0 : getToasstyoygrowrate().hashCode());
        result = prime * result + ((getToliablt() == null) ? 0 : getToliablt().hashCode());
        result = prime * result + ((getToliabltyoygrowrate() == null) ? 0 : getToliabltyoygrowrate().hashCode());
        result = prime * result + ((getSharehldrigint() == null) ? 0 : getSharehldrigint().hashCode());
        result = prime * result + ((getSharehldrigintyoygrowrate() == null) ? 0 : getSharehldrigintyoygrowrate().hashCode());
        result = prime * result + ((getNetcshflow() == null) ? 0 : getNetcshflow().hashCode());
        result = prime * result + ((getNetcshfloperact() == null) ? 0 : getNetcshfloperact().hashCode());
        result = prime * result + ((getNetcshflinvact() == null) ? 0 : getNetcshflinvact().hashCode());
        result = prime * result + ((getNetcshflfinact() == null) ? 0 : getNetcshflfinact().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", toinc=").append(toinc);
        sb.append(", toincyoygrowrate=").append(toincyoygrowrate);
        sb.append(", netpro=").append(netpro);
        sb.append(", netproyoygrowrate=").append(netproyoygrowrate);
        sb.append(", ebit=").append(ebit);
        sb.append(", ebitda=").append(ebitda);
        sb.append(", toasst=").append(toasst);
        sb.append(", toasstyoygrowrate=").append(toasstyoygrowrate);
        sb.append(", toliablt=").append(toliablt);
        sb.append(", toliabltyoygrowrate=").append(toliabltyoygrowrate);
        sb.append(", sharehldrigint=").append(sharehldrigint);
        sb.append(", sharehldrigintyoygrowrate=").append(sharehldrigintyoygrowrate);
        sb.append(", netcshflow=").append(netcshflow);
        sb.append(", netcshfloperact=").append(netcshfloperact);
        sb.append(", netcshflinvact=").append(netcshflinvact);
        sb.append(", netcshflfinact=").append(netcshflfinact);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}