package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ComparisonOfValuationPerformance_otherAttributes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.securCode
     *
     * @mbggenerated
     */
    private String securcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.latstClosDay
     *
     * @mbggenerated
     */
    private String latstclosday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.toMaktVal
     *
     * @mbggenerated
     */
    private String tomaktval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.marktValOfCircul
     *
     * @mbggenerated
     */
    private String marktvalofcircul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.PBMRQ
     *
     * @mbggenerated
     */
    private String pbmrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.PCFTTM
     *
     * @mbggenerated
     */
    private String pcfttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.PSTTM
     *
     * @mbggenerated
     */
    private String psttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.entpMarktVal
     *
     * @mbggenerated
     */
    private String entpmarktval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.emvIncRat
     *
     * @mbggenerated
     */
    private String emvincrat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 估值表现分析其他属性.emvEBITDARat
     *
     * @mbggenerated
     */
    private String emvebitdarat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 估值表现分析其他属性
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.securCode
     *
     * @return the value of 估值表现分析其他属性.securCode
     *
     * @mbggenerated
     */
    public String getSecurcode() {
        return securcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.securCode
     *
     * @param securcode the value for 估值表现分析其他属性.securCode
     *
     * @mbggenerated
     */
    public void setSecurcode(String securcode) {
        this.securcode = securcode == null ? null : securcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.latstClosDay
     *
     * @return the value of 估值表现分析其他属性.latstClosDay
     *
     * @mbggenerated
     */
    public String getLatstclosday() {
        return latstclosday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.latstClosDay
     *
     * @param latstclosday the value for 估值表现分析其他属性.latstClosDay
     *
     * @mbggenerated
     */
    public void setLatstclosday(String latstclosday) {
        this.latstclosday = latstclosday == null ? null : latstclosday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.toMaktVal
     *
     * @return the value of 估值表现分析其他属性.toMaktVal
     *
     * @mbggenerated
     */
    public String getTomaktval() {
        return tomaktval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.toMaktVal
     *
     * @param tomaktval the value for 估值表现分析其他属性.toMaktVal
     *
     * @mbggenerated
     */
    public void setTomaktval(String tomaktval) {
        this.tomaktval = tomaktval == null ? null : tomaktval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.marktValOfCircul
     *
     * @return the value of 估值表现分析其他属性.marktValOfCircul
     *
     * @mbggenerated
     */
    public String getMarktvalofcircul() {
        return marktvalofcircul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.marktValOfCircul
     *
     * @param marktvalofcircul the value for 估值表现分析其他属性.marktValOfCircul
     *
     * @mbggenerated
     */
    public void setMarktvalofcircul(String marktvalofcircul) {
        this.marktvalofcircul = marktvalofcircul == null ? null : marktvalofcircul.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.PBMRQ
     *
     * @return the value of 估值表现分析其他属性.PBMRQ
     *
     * @mbggenerated
     */
    public String getPbmrq() {
        return pbmrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.PBMRQ
     *
     * @param pbmrq the value for 估值表现分析其他属性.PBMRQ
     *
     * @mbggenerated
     */
    public void setPbmrq(String pbmrq) {
        this.pbmrq = pbmrq == null ? null : pbmrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.PCFTTM
     *
     * @return the value of 估值表现分析其他属性.PCFTTM
     *
     * @mbggenerated
     */
    public String getPcfttm() {
        return pcfttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.PCFTTM
     *
     * @param pcfttm the value for 估值表现分析其他属性.PCFTTM
     *
     * @mbggenerated
     */
    public void setPcfttm(String pcfttm) {
        this.pcfttm = pcfttm == null ? null : pcfttm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.PSTTM
     *
     * @return the value of 估值表现分析其他属性.PSTTM
     *
     * @mbggenerated
     */
    public String getPsttm() {
        return psttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.PSTTM
     *
     * @param psttm the value for 估值表现分析其他属性.PSTTM
     *
     * @mbggenerated
     */
    public void setPsttm(String psttm) {
        this.psttm = psttm == null ? null : psttm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.entpMarktVal
     *
     * @return the value of 估值表现分析其他属性.entpMarktVal
     *
     * @mbggenerated
     */
    public String getEntpmarktval() {
        return entpmarktval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.entpMarktVal
     *
     * @param entpmarktval the value for 估值表现分析其他属性.entpMarktVal
     *
     * @mbggenerated
     */
    public void setEntpmarktval(String entpmarktval) {
        this.entpmarktval = entpmarktval == null ? null : entpmarktval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.emvIncRat
     *
     * @return the value of 估值表现分析其他属性.emvIncRat
     *
     * @mbggenerated
     */
    public String getEmvincrat() {
        return emvincrat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.emvIncRat
     *
     * @param emvincrat the value for 估值表现分析其他属性.emvIncRat
     *
     * @mbggenerated
     */
    public void setEmvincrat(String emvincrat) {
        this.emvincrat = emvincrat == null ? null : emvincrat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 估值表现分析其他属性.emvEBITDARat
     *
     * @return the value of 估值表现分析其他属性.emvEBITDARat
     *
     * @mbggenerated
     */
    public String getEmvebitdarat() {
        return emvebitdarat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 估值表现分析其他属性.emvEBITDARat
     *
     * @param emvebitdarat the value for 估值表现分析其他属性.emvEBITDARat
     *
     * @mbggenerated
     */
    public void setEmvebitdarat(String emvebitdarat) {
        this.emvebitdarat = emvebitdarat == null ? null : emvebitdarat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析其他属性
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfValuationPerformance_otherAttributes other = (ComparisonOfValuationPerformance_otherAttributes) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getLatstclosday() == null ? other.getLatstclosday() == null : this.getLatstclosday().equals(other.getLatstclosday()))
            && (this.getTomaktval() == null ? other.getTomaktval() == null : this.getTomaktval().equals(other.getTomaktval()))
            && (this.getMarktvalofcircul() == null ? other.getMarktvalofcircul() == null : this.getMarktvalofcircul().equals(other.getMarktvalofcircul()))
            && (this.getPbmrq() == null ? other.getPbmrq() == null : this.getPbmrq().equals(other.getPbmrq()))
            && (this.getPcfttm() == null ? other.getPcfttm() == null : this.getPcfttm().equals(other.getPcfttm()))
            && (this.getPsttm() == null ? other.getPsttm() == null : this.getPsttm().equals(other.getPsttm()))
            && (this.getEntpmarktval() == null ? other.getEntpmarktval() == null : this.getEntpmarktval().equals(other.getEntpmarktval()))
            && (this.getEmvincrat() == null ? other.getEmvincrat() == null : this.getEmvincrat().equals(other.getEmvincrat()))
            && (this.getEmvebitdarat() == null ? other.getEmvebitdarat() == null : this.getEmvebitdarat().equals(other.getEmvebitdarat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析其他属性
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getLatstclosday() == null) ? 0 : getLatstclosday().hashCode());
        result = prime * result + ((getTomaktval() == null) ? 0 : getTomaktval().hashCode());
        result = prime * result + ((getMarktvalofcircul() == null) ? 0 : getMarktvalofcircul().hashCode());
        result = prime * result + ((getPbmrq() == null) ? 0 : getPbmrq().hashCode());
        result = prime * result + ((getPcfttm() == null) ? 0 : getPcfttm().hashCode());
        result = prime * result + ((getPsttm() == null) ? 0 : getPsttm().hashCode());
        result = prime * result + ((getEntpmarktval() == null) ? 0 : getEntpmarktval().hashCode());
        result = prime * result + ((getEmvincrat() == null) ? 0 : getEmvincrat().hashCode());
        result = prime * result + ((getEmvebitdarat() == null) ? 0 : getEmvebitdarat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析其他属性
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", securcode=").append(securcode);
        sb.append(", latstclosday=").append(latstclosday);
        sb.append(", tomaktval=").append(tomaktval);
        sb.append(", marktvalofcircul=").append(marktvalofcircul);
        sb.append(", pbmrq=").append(pbmrq);
        sb.append(", pcfttm=").append(pcfttm);
        sb.append(", psttm=").append(psttm);
        sb.append(", entpmarktval=").append(entpmarktval);
        sb.append(", emvincrat=").append(emvincrat);
        sb.append(", emvebitdarat=").append(emvebitdarat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}