package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ComparisonOfIndustryHistory_newThirdBoard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.PE
     *
     * @mbggenerated
     */
    private String pe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.PB
     *
     * @mbggenerated
     */
    private String pb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.PS
     *
     * @mbggenerated
     */
    private String ps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.sinQuarRevenPro
     *
     * @mbggenerated
     */
    private String sinquarrevenpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.sinQuarNetPro
     *
     * @mbggenerated
     */
    private String sinquarnetpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.sinQuarNetInRate
     *
     * @mbggenerated
     */
    private String sinquarnetinrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.sinQuarROE
     *
     * @mbggenerated
     */
    private String sinquarroe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业历史比较新三板做市.sinQuarROA
     *
     * @mbggenerated
     */
    private String sinquarroa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 行业历史比较新三板做市
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.time
     *
     * @return the value of 行业历史比较新三板做市.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.time
     *
     * @param time the value for 行业历史比较新三板做市.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.PE
     *
     * @return the value of 行业历史比较新三板做市.PE
     *
     * @mbggenerated
     */
    public String getPe() {
        return pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.PE
     *
     * @param pe the value for 行业历史比较新三板做市.PE
     *
     * @mbggenerated
     */
    public void setPe(String pe) {
        this.pe = pe == null ? null : pe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.PB
     *
     * @return the value of 行业历史比较新三板做市.PB
     *
     * @mbggenerated
     */
    public String getPb() {
        return pb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.PB
     *
     * @param pb the value for 行业历史比较新三板做市.PB
     *
     * @mbggenerated
     */
    public void setPb(String pb) {
        this.pb = pb == null ? null : pb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.PS
     *
     * @return the value of 行业历史比较新三板做市.PS
     *
     * @mbggenerated
     */
    public String getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.PS
     *
     * @param ps the value for 行业历史比较新三板做市.PS
     *
     * @mbggenerated
     */
    public void setPs(String ps) {
        this.ps = ps == null ? null : ps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.sinQuarRevenPro
     *
     * @return the value of 行业历史比较新三板做市.sinQuarRevenPro
     *
     * @mbggenerated
     */
    public String getSinquarrevenpro() {
        return sinquarrevenpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.sinQuarRevenPro
     *
     * @param sinquarrevenpro the value for 行业历史比较新三板做市.sinQuarRevenPro
     *
     * @mbggenerated
     */
    public void setSinquarrevenpro(String sinquarrevenpro) {
        this.sinquarrevenpro = sinquarrevenpro == null ? null : sinquarrevenpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.sinQuarNetPro
     *
     * @return the value of 行业历史比较新三板做市.sinQuarNetPro
     *
     * @mbggenerated
     */
    public String getSinquarnetpro() {
        return sinquarnetpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.sinQuarNetPro
     *
     * @param sinquarnetpro the value for 行业历史比较新三板做市.sinQuarNetPro
     *
     * @mbggenerated
     */
    public void setSinquarnetpro(String sinquarnetpro) {
        this.sinquarnetpro = sinquarnetpro == null ? null : sinquarnetpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.sinQuarNetInRate
     *
     * @return the value of 行业历史比较新三板做市.sinQuarNetInRate
     *
     * @mbggenerated
     */
    public String getSinquarnetinrate() {
        return sinquarnetinrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.sinQuarNetInRate
     *
     * @param sinquarnetinrate the value for 行业历史比较新三板做市.sinQuarNetInRate
     *
     * @mbggenerated
     */
    public void setSinquarnetinrate(String sinquarnetinrate) {
        this.sinquarnetinrate = sinquarnetinrate == null ? null : sinquarnetinrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.sinQuarROE
     *
     * @return the value of 行业历史比较新三板做市.sinQuarROE
     *
     * @mbggenerated
     */
    public String getSinquarroe() {
        return sinquarroe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.sinQuarROE
     *
     * @param sinquarroe the value for 行业历史比较新三板做市.sinQuarROE
     *
     * @mbggenerated
     */
    public void setSinquarroe(String sinquarroe) {
        this.sinquarroe = sinquarroe == null ? null : sinquarroe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业历史比较新三板做市.sinQuarROA
     *
     * @return the value of 行业历史比较新三板做市.sinQuarROA
     *
     * @mbggenerated
     */
    public String getSinquarroa() {
        return sinquarroa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业历史比较新三板做市.sinQuarROA
     *
     * @param sinquarroa the value for 行业历史比较新三板做市.sinQuarROA
     *
     * @mbggenerated
     */
    public void setSinquarroa(String sinquarroa) {
        this.sinquarroa = sinquarroa == null ? null : sinquarroa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较新三板做市
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfIndustryHistory_newThirdBoard other = (ComparisonOfIndustryHistory_newThirdBoard) that;
        return (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getPe() == null ? other.getPe() == null : this.getPe().equals(other.getPe()))
            && (this.getPb() == null ? other.getPb() == null : this.getPb().equals(other.getPb()))
            && (this.getPs() == null ? other.getPs() == null : this.getPs().equals(other.getPs()))
            && (this.getSinquarrevenpro() == null ? other.getSinquarrevenpro() == null : this.getSinquarrevenpro().equals(other.getSinquarrevenpro()))
            && (this.getSinquarnetpro() == null ? other.getSinquarnetpro() == null : this.getSinquarnetpro().equals(other.getSinquarnetpro()))
            && (this.getSinquarnetinrate() == null ? other.getSinquarnetinrate() == null : this.getSinquarnetinrate().equals(other.getSinquarnetinrate()))
            && (this.getSinquarroe() == null ? other.getSinquarroe() == null : this.getSinquarroe().equals(other.getSinquarroe()))
            && (this.getSinquarroa() == null ? other.getSinquarroa() == null : this.getSinquarroa().equals(other.getSinquarroa()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较新三板做市
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getPe() == null) ? 0 : getPe().hashCode());
        result = prime * result + ((getPb() == null) ? 0 : getPb().hashCode());
        result = prime * result + ((getPs() == null) ? 0 : getPs().hashCode());
        result = prime * result + ((getSinquarrevenpro() == null) ? 0 : getSinquarrevenpro().hashCode());
        result = prime * result + ((getSinquarnetpro() == null) ? 0 : getSinquarnetpro().hashCode());
        result = prime * result + ((getSinquarnetinrate() == null) ? 0 : getSinquarnetinrate().hashCode());
        result = prime * result + ((getSinquarroe() == null) ? 0 : getSinquarroe().hashCode());
        result = prime * result + ((getSinquarroa() == null) ? 0 : getSinquarroa().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较新三板做市
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", time=").append(time);
        sb.append(", pe=").append(pe);
        sb.append(", pb=").append(pb);
        sb.append(", ps=").append(ps);
        sb.append(", sinquarrevenpro=").append(sinquarrevenpro);
        sb.append(", sinquarnetpro=").append(sinquarnetpro);
        sb.append(", sinquarnetinrate=").append(sinquarnetinrate);
        sb.append(", sinquarroe=").append(sinquarroe);
        sb.append(", sinquarroa=").append(sinquarroa);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}