package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ComparisonOfFinancialData_splitTableKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.securCode
     *
     * @mbggenerated
     */
    private String securcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 财务数据比较-拆分表.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.securCode
     *
     * @return the value of 财务数据比较-拆分表.securCode
     *
     * @mbggenerated
     */
    public String getSecurcode() {
        return securcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.securCode
     *
     * @param securcode the value for 财务数据比较-拆分表.securCode
     *
     * @mbggenerated
     */
    public void setSecurcode(String securcode) {
        this.securcode = securcode == null ? null : securcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 财务数据比较-拆分表.year
     *
     * @return the value of 财务数据比较-拆分表.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 财务数据比较-拆分表.year
     *
     * @param year the value for 财务数据比较-拆分表.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ComparisonOfFinancialData_splitTableKey other = (ComparisonOfFinancialData_splitTableKey) that;
        return (this.getSecurcode() == null ? other.getSecurcode() == null : this.getSecurcode().equals(other.getSecurcode()))
            && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSecurcode() == null) ? 0 : getSecurcode().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较-拆分表
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", securcode=").append(securcode);
        sb.append(", year=").append(year);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}