package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class ContrastOfMarketPerformance_all implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.indstNam
     *
     * @mbggenerated
     */
    private String indstnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.nearAWkRiseFal
     *
     * @mbggenerated
     */
    private String nearawkrisefal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.nearAMthRiseFal
     *
     * @mbggenerated
     */
    private String nearamthrisefal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.nearThrMthRiseFal
     *
     * @mbggenerated
     */
    private String nearthrmthrisefal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.ydtRiseFal
     *
     * @mbggenerated
     */
    private String ydtrisefal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 市场表现对比全部.nearAYearRiseFal
     *
     * @mbggenerated
     */
    private String nearayearrisefal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 市场表现对比全部
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.indstNam
     *
     * @return the value of 市场表现对比全部.indstNam
     *
     * @mbggenerated
     */
    public String getIndstnam() {
        return indstnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.indstNam
     *
     * @param indstnam the value for 市场表现对比全部.indstNam
     *
     * @mbggenerated
     */
    public void setIndstnam(String indstnam) {
        this.indstnam = indstnam == null ? null : indstnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.nearAWkRiseFal
     *
     * @return the value of 市场表现对比全部.nearAWkRiseFal
     *
     * @mbggenerated
     */
    public String getNearawkrisefal() {
        return nearawkrisefal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.nearAWkRiseFal
     *
     * @param nearawkrisefal the value for 市场表现对比全部.nearAWkRiseFal
     *
     * @mbggenerated
     */
    public void setNearawkrisefal(String nearawkrisefal) {
        this.nearawkrisefal = nearawkrisefal == null ? null : nearawkrisefal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.nearAMthRiseFal
     *
     * @return the value of 市场表现对比全部.nearAMthRiseFal
     *
     * @mbggenerated
     */
    public String getNearamthrisefal() {
        return nearamthrisefal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.nearAMthRiseFal
     *
     * @param nearamthrisefal the value for 市场表现对比全部.nearAMthRiseFal
     *
     * @mbggenerated
     */
    public void setNearamthrisefal(String nearamthrisefal) {
        this.nearamthrisefal = nearamthrisefal == null ? null : nearamthrisefal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.nearThrMthRiseFal
     *
     * @return the value of 市场表现对比全部.nearThrMthRiseFal
     *
     * @mbggenerated
     */
    public String getNearthrmthrisefal() {
        return nearthrmthrisefal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.nearThrMthRiseFal
     *
     * @param nearthrmthrisefal the value for 市场表现对比全部.nearThrMthRiseFal
     *
     * @mbggenerated
     */
    public void setNearthrmthrisefal(String nearthrmthrisefal) {
        this.nearthrmthrisefal = nearthrmthrisefal == null ? null : nearthrmthrisefal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.ydtRiseFal
     *
     * @return the value of 市场表现对比全部.ydtRiseFal
     *
     * @mbggenerated
     */
    public String getYdtrisefal() {
        return ydtrisefal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.ydtRiseFal
     *
     * @param ydtrisefal the value for 市场表现对比全部.ydtRiseFal
     *
     * @mbggenerated
     */
    public void setYdtrisefal(String ydtrisefal) {
        this.ydtrisefal = ydtrisefal == null ? null : ydtrisefal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 市场表现对比全部.nearAYearRiseFal
     *
     * @return the value of 市场表现对比全部.nearAYearRiseFal
     *
     * @mbggenerated
     */
    public String getNearayearrisefal() {
        return nearayearrisefal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 市场表现对比全部.nearAYearRiseFal
     *
     * @param nearayearrisefal the value for 市场表现对比全部.nearAYearRiseFal
     *
     * @mbggenerated
     */
    public void setNearayearrisefal(String nearayearrisefal) {
        this.nearayearrisefal = nearayearrisefal == null ? null : nearayearrisefal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比全部
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContrastOfMarketPerformance_all other = (ContrastOfMarketPerformance_all) that;
        return (this.getIndstnam() == null ? other.getIndstnam() == null : this.getIndstnam().equals(other.getIndstnam()))
            && (this.getNearawkrisefal() == null ? other.getNearawkrisefal() == null : this.getNearawkrisefal().equals(other.getNearawkrisefal()))
            && (this.getNearamthrisefal() == null ? other.getNearamthrisefal() == null : this.getNearamthrisefal().equals(other.getNearamthrisefal()))
            && (this.getNearthrmthrisefal() == null ? other.getNearthrmthrisefal() == null : this.getNearthrmthrisefal().equals(other.getNearthrmthrisefal()))
            && (this.getYdtrisefal() == null ? other.getYdtrisefal() == null : this.getYdtrisefal().equals(other.getYdtrisefal()))
            && (this.getNearayearrisefal() == null ? other.getNearayearrisefal() == null : this.getNearayearrisefal().equals(other.getNearayearrisefal()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比全部
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIndstnam() == null) ? 0 : getIndstnam().hashCode());
        result = prime * result + ((getNearawkrisefal() == null) ? 0 : getNearawkrisefal().hashCode());
        result = prime * result + ((getNearamthrisefal() == null) ? 0 : getNearamthrisefal().hashCode());
        result = prime * result + ((getNearthrmthrisefal() == null) ? 0 : getNearthrmthrisefal().hashCode());
        result = prime * result + ((getYdtrisefal() == null) ? 0 : getYdtrisefal().hashCode());
        result = prime * result + ((getNearayearrisefal() == null) ? 0 : getNearayearrisefal().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比全部
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", indstnam=").append(indstnam);
        sb.append(", nearawkrisefal=").append(nearawkrisefal);
        sb.append(", nearamthrisefal=").append(nearamthrisefal);
        sb.append(", nearthrmthrisefal=").append(nearthrmthrisefal);
        sb.append(", ydtrisefal=").append(ydtrisefal);
        sb.append(", nearayearrisefal=").append(nearayearrisefal);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}