package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class QuickRatio extends QuickRatioKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 速动比率.quiRitio
     *
     * @mbggenerated
     */
    private String quiritio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 速动比率
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 速动比率.quiRitio
     *
     * @return the value of 速动比率.quiRitio
     *
     * @mbggenerated
     */
    public String getQuiritio() {
        return quiritio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 速动比率.quiRitio
     *
     * @param quiritio the value for 速动比率.quiRitio
     *
     * @mbggenerated
     */
    public void setQuiritio(String quiritio) {
        this.quiritio = quiritio == null ? null : quiritio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 速动比率
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuickRatio other = (QuickRatio) that;
        return (this.getStkcd() == null ? other.getStkcd() == null : this.getStkcd().equals(other.getStkcd()))
            && (this.getAcceper() == null ? other.getAcceper() == null : this.getAcceper().equals(other.getAcceper()))
            && (this.getQuiritio() == null ? other.getQuiritio() == null : this.getQuiritio().equals(other.getQuiritio()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 速动比率
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStkcd() == null) ? 0 : getStkcd().hashCode());
        result = prime * result + ((getAcceper() == null) ? 0 : getAcceper().hashCode());
        result = prime * result + ((getQuiritio() == null) ? 0 : getQuiritio().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 速动比率
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", quiritio=").append(quiritio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}