package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class StatusOfIndustryListing_newThirdBoard implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.indstNam
     *
     * @mbggenerated
     */
    private String indstnam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.PETTM
     *
     * @mbggenerated
     */
    private String pettm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.PEYearFcast
     *
     * @mbggenerated
     */
    private String peyearfcast;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.PBLF
     *
     * @mbggenerated
     */
    private String pblf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.PSTTM
     *
     * @mbggenerated
     */
    private String psttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.ROETTM
     *
     * @mbggenerated
     */
    private String roettm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.ROATTM
     *
     * @mbggenerated
     */
    private String roattm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.netPro
     *
     * @mbggenerated
     */
    private String netpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.revenPro
     *
     * @mbggenerated
     */
    private String revenpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.toMaktVal
     *
     * @mbggenerated
     */
    private String tomaktval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.businsInc
     *
     * @mbggenerated
     */
    private String businsinc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 行业上市地位新三板做市.toAssets
     *
     * @mbggenerated
     */
    private String toassets;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 行业上市地位新三板做市
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.indstNam
     *
     * @return the value of 行业上市地位新三板做市.indstNam
     *
     * @mbggenerated
     */
    public String getIndstnam() {
        return indstnam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.indstNam
     *
     * @param indstnam the value for 行业上市地位新三板做市.indstNam
     *
     * @mbggenerated
     */
    public void setIndstnam(String indstnam) {
        this.indstnam = indstnam == null ? null : indstnam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.PETTM
     *
     * @return the value of 行业上市地位新三板做市.PETTM
     *
     * @mbggenerated
     */
    public String getPettm() {
        return pettm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.PETTM
     *
     * @param pettm the value for 行业上市地位新三板做市.PETTM
     *
     * @mbggenerated
     */
    public void setPettm(String pettm) {
        this.pettm = pettm == null ? null : pettm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.PEYearFcast
     *
     * @return the value of 行业上市地位新三板做市.PEYearFcast
     *
     * @mbggenerated
     */
    public String getPeyearfcast() {
        return peyearfcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.PEYearFcast
     *
     * @param peyearfcast the value for 行业上市地位新三板做市.PEYearFcast
     *
     * @mbggenerated
     */
    public void setPeyearfcast(String peyearfcast) {
        this.peyearfcast = peyearfcast == null ? null : peyearfcast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.PBLF
     *
     * @return the value of 行业上市地位新三板做市.PBLF
     *
     * @mbggenerated
     */
    public String getPblf() {
        return pblf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.PBLF
     *
     * @param pblf the value for 行业上市地位新三板做市.PBLF
     *
     * @mbggenerated
     */
    public void setPblf(String pblf) {
        this.pblf = pblf == null ? null : pblf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.PSTTM
     *
     * @return the value of 行业上市地位新三板做市.PSTTM
     *
     * @mbggenerated
     */
    public String getPsttm() {
        return psttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.PSTTM
     *
     * @param psttm the value for 行业上市地位新三板做市.PSTTM
     *
     * @mbggenerated
     */
    public void setPsttm(String psttm) {
        this.psttm = psttm == null ? null : psttm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.ROETTM
     *
     * @return the value of 行业上市地位新三板做市.ROETTM
     *
     * @mbggenerated
     */
    public String getRoettm() {
        return roettm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.ROETTM
     *
     * @param roettm the value for 行业上市地位新三板做市.ROETTM
     *
     * @mbggenerated
     */
    public void setRoettm(String roettm) {
        this.roettm = roettm == null ? null : roettm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.ROATTM
     *
     * @return the value of 行业上市地位新三板做市.ROATTM
     *
     * @mbggenerated
     */
    public String getRoattm() {
        return roattm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.ROATTM
     *
     * @param roattm the value for 行业上市地位新三板做市.ROATTM
     *
     * @mbggenerated
     */
    public void setRoattm(String roattm) {
        this.roattm = roattm == null ? null : roattm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.netPro
     *
     * @return the value of 行业上市地位新三板做市.netPro
     *
     * @mbggenerated
     */
    public String getNetpro() {
        return netpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.netPro
     *
     * @param netpro the value for 行业上市地位新三板做市.netPro
     *
     * @mbggenerated
     */
    public void setNetpro(String netpro) {
        this.netpro = netpro == null ? null : netpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.revenPro
     *
     * @return the value of 行业上市地位新三板做市.revenPro
     *
     * @mbggenerated
     */
    public String getRevenpro() {
        return revenpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.revenPro
     *
     * @param revenpro the value for 行业上市地位新三板做市.revenPro
     *
     * @mbggenerated
     */
    public void setRevenpro(String revenpro) {
        this.revenpro = revenpro == null ? null : revenpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.toMaktVal
     *
     * @return the value of 行业上市地位新三板做市.toMaktVal
     *
     * @mbggenerated
     */
    public String getTomaktval() {
        return tomaktval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.toMaktVal
     *
     * @param tomaktval the value for 行业上市地位新三板做市.toMaktVal
     *
     * @mbggenerated
     */
    public void setTomaktval(String tomaktval) {
        this.tomaktval = tomaktval == null ? null : tomaktval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.businsInc
     *
     * @return the value of 行业上市地位新三板做市.businsInc
     *
     * @mbggenerated
     */
    public String getBusinsinc() {
        return businsinc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.businsInc
     *
     * @param businsinc the value for 行业上市地位新三板做市.businsInc
     *
     * @mbggenerated
     */
    public void setBusinsinc(String businsinc) {
        this.businsinc = businsinc == null ? null : businsinc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 行业上市地位新三板做市.toAssets
     *
     * @return the value of 行业上市地位新三板做市.toAssets
     *
     * @mbggenerated
     */
    public String getToassets() {
        return toassets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 行业上市地位新三板做市.toAssets
     *
     * @param toassets the value for 行业上市地位新三板做市.toAssets
     *
     * @mbggenerated
     */
    public void setToassets(String toassets) {
        this.toassets = toassets == null ? null : toassets.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位新三板做市
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StatusOfIndustryListing_newThirdBoard other = (StatusOfIndustryListing_newThirdBoard) that;
        return (this.getIndstnam() == null ? other.getIndstnam() == null : this.getIndstnam().equals(other.getIndstnam()))
            && (this.getPettm() == null ? other.getPettm() == null : this.getPettm().equals(other.getPettm()))
            && (this.getPeyearfcast() == null ? other.getPeyearfcast() == null : this.getPeyearfcast().equals(other.getPeyearfcast()))
            && (this.getPblf() == null ? other.getPblf() == null : this.getPblf().equals(other.getPblf()))
            && (this.getPsttm() == null ? other.getPsttm() == null : this.getPsttm().equals(other.getPsttm()))
            && (this.getRoettm() == null ? other.getRoettm() == null : this.getRoettm().equals(other.getRoettm()))
            && (this.getRoattm() == null ? other.getRoattm() == null : this.getRoattm().equals(other.getRoattm()))
            && (this.getNetpro() == null ? other.getNetpro() == null : this.getNetpro().equals(other.getNetpro()))
            && (this.getRevenpro() == null ? other.getRevenpro() == null : this.getRevenpro().equals(other.getRevenpro()))
            && (this.getTomaktval() == null ? other.getTomaktval() == null : this.getTomaktval().equals(other.getTomaktval()))
            && (this.getBusinsinc() == null ? other.getBusinsinc() == null : this.getBusinsinc().equals(other.getBusinsinc()))
            && (this.getToassets() == null ? other.getToassets() == null : this.getToassets().equals(other.getToassets()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位新三板做市
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIndstnam() == null) ? 0 : getIndstnam().hashCode());
        result = prime * result + ((getPettm() == null) ? 0 : getPettm().hashCode());
        result = prime * result + ((getPeyearfcast() == null) ? 0 : getPeyearfcast().hashCode());
        result = prime * result + ((getPblf() == null) ? 0 : getPblf().hashCode());
        result = prime * result + ((getPsttm() == null) ? 0 : getPsttm().hashCode());
        result = prime * result + ((getRoettm() == null) ? 0 : getRoettm().hashCode());
        result = prime * result + ((getRoattm() == null) ? 0 : getRoattm().hashCode());
        result = prime * result + ((getNetpro() == null) ? 0 : getNetpro().hashCode());
        result = prime * result + ((getRevenpro() == null) ? 0 : getRevenpro().hashCode());
        result = prime * result + ((getTomaktval() == null) ? 0 : getTomaktval().hashCode());
        result = prime * result + ((getBusinsinc() == null) ? 0 : getBusinsinc().hashCode());
        result = prime * result + ((getToassets() == null) ? 0 : getToassets().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位新三板做市
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", indstnam=").append(indstnam);
        sb.append(", pettm=").append(pettm);
        sb.append(", peyearfcast=").append(peyearfcast);
        sb.append(", pblf=").append(pblf);
        sb.append(", psttm=").append(psttm);
        sb.append(", roettm=").append(roettm);
        sb.append(", roattm=").append(roattm);
        sb.append(", netpro=").append(netpro);
        sb.append(", revenpro=").append(revenpro);
        sb.append(", tomaktval=").append(tomaktval);
        sb.append(", businsinc=").append(businsinc);
        sb.append(", toassets=").append(toassets);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}