package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class TheGlobalPassengerCarSales implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 全球乘用车销量.f1
     *
     * @mbggenerated
     */
    private String f1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 全球乘用车销量.passSalesWorld
     *
     * @mbggenerated
     */
    private String passsalesworld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 全球乘用车销量.passSalesEur
     *
     * @mbggenerated
     */
    private String passsaleseur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 全球乘用车销量
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 全球乘用车销量.f1
     *
     * @return the value of 全球乘用车销量.f1
     *
     * @mbggenerated
     */
    public String getF1() {
        return f1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 全球乘用车销量.f1
     *
     * @param f1 the value for 全球乘用车销量.f1
     *
     * @mbggenerated
     */
    public void setF1(String f1) {
        this.f1 = f1 == null ? null : f1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 全球乘用车销量.passSalesWorld
     *
     * @return the value of 全球乘用车销量.passSalesWorld
     *
     * @mbggenerated
     */
    public String getPasssalesworld() {
        return passsalesworld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 全球乘用车销量.passSalesWorld
     *
     * @param passsalesworld the value for 全球乘用车销量.passSalesWorld
     *
     * @mbggenerated
     */
    public void setPasssalesworld(String passsalesworld) {
        this.passsalesworld = passsalesworld == null ? null : passsalesworld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 全球乘用车销量.passSalesEur
     *
     * @return the value of 全球乘用车销量.passSalesEur
     *
     * @mbggenerated
     */
    public String getPasssaleseur() {
        return passsaleseur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 全球乘用车销量.passSalesEur
     *
     * @param passsaleseur the value for 全球乘用车销量.passSalesEur
     *
     * @mbggenerated
     */
    public void setPasssaleseur(String passsaleseur) {
        this.passsaleseur = passsaleseur == null ? null : passsaleseur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球乘用车销量
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TheGlobalPassengerCarSales other = (TheGlobalPassengerCarSales) that;
        return (this.getF1() == null ? other.getF1() == null : this.getF1().equals(other.getF1()))
            && (this.getPasssalesworld() == null ? other.getPasssalesworld() == null : this.getPasssalesworld().equals(other.getPasssalesworld()))
            && (this.getPasssaleseur() == null ? other.getPasssaleseur() == null : this.getPasssaleseur().equals(other.getPasssaleseur()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球乘用车销量
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getF1() == null) ? 0 : getF1().hashCode());
        result = prime * result + ((getPasssalesworld() == null) ? 0 : getPasssalesworld().hashCode());
        result = prime * result + ((getPasssaleseur() == null) ? 0 : getPasssaleseur().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球乘用车销量
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", f1=").append(f1);
        sb.append(", passsalesworld=").append(passsalesworld);
        sb.append(", passsaleseur=").append(passsaleseur);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}