package com.citicup.model.dataDisplay;

import java.io.Serializable;

public class WorkingCapitalAndLoanRatio extends WorkingCapitalAndLoanRatioKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 营运资金与借款比.workCapAndLoanRatio
     *
     * @mbggenerated
     */
    private String workcapandloanratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 营运资金与借款比.workCapAndLoanRatio
     *
     * @return the value of 营运资金与借款比.workCapAndLoanRatio
     *
     * @mbggenerated
     */
    public String getWorkcapandloanratio() {
        return workcapandloanratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 营运资金与借款比.workCapAndLoanRatio
     *
     * @param workcapandloanratio the value for 营运资金与借款比.workCapAndLoanRatio
     *
     * @mbggenerated
     */
    public void setWorkcapandloanratio(String workcapandloanratio) {
        this.workcapandloanratio = workcapandloanratio == null ? null : workcapandloanratio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WorkingCapitalAndLoanRatio other = (WorkingCapitalAndLoanRatio) that;
        return (this.getStkcd() == null ? other.getStkcd() == null : this.getStkcd().equals(other.getStkcd()))
            && (this.getAcceper() == null ? other.getAcceper() == null : this.getAcceper().equals(other.getAcceper()))
            && (this.getWorkcapandloanratio() == null ? other.getWorkcapandloanratio() == null : this.getWorkcapandloanratio().equals(other.getWorkcapandloanratio()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getStkcd() == null) ? 0 : getStkcd().hashCode());
        result = prime * result + ((getAcceper() == null) ? 0 : getAcceper().hashCode());
        result = prime * result + ((getWorkcapandloanratio() == null) ? 0 : getWorkcapandloanratio().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workcapandloanratio=").append(workcapandloanratio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}