package com.citicup.dao;

import com.citicup.model.AmericanCarSales;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AmericanCarSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    int insert(AmericanCarSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    int insertSelective(AmericanCarSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    AmericanCarSales selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AmericanCarSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 美国汽车销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AmericanCarSales record);

    @Select("SELECT * FROM citicup.美国汽车销量")
    List<AmericanCarSales> getAll();
}