package com.citicup.dao;

import com.citicup.model.AutomobileIndustryPolicyTrends;
import com.citicup.model.AutomobileIndustryPolicyTrendsKey;

public interface AutomobileIndustryPolicyTrendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AutomobileIndustryPolicyTrendsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int insert(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int insertSelective(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    AutomobileIndustryPolicyTrends selectByPrimaryKey(AutomobileIndustryPolicyTrendsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutomobileIndustryPolicyTrends record);
}