package com.citicup.dao;

import com.citicup.model.AverageAccountsReceivableTurnoverRatio;
import com.citicup.model.AverageAccountsReceivableTurnoverRatioKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AverageAccountsReceivableTurnoverRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AverageAccountsReceivableTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    int insert(AverageAccountsReceivableTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    int insertSelective(AverageAccountsReceivableTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    AverageAccountsReceivableTurnoverRatio selectByPrimaryKey(AverageAccountsReceivableTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AverageAccountsReceivableTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 应收账款周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AverageAccountsReceivableTurnoverRatio record);

    @Select("SELECT * FROM citicup.应收账款周转率")
    List<AverageAccountsReceivableTurnoverRatio> getAll();
}