package com.citicup.dao;

import com.citicup.model.AverageNumberOfEmployeesInChinaAutoIndustry;

public interface AverageNumberOfEmployeesInChinaAutoIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    int insert(AverageNumberOfEmployeesInChinaAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    int insertSelective(AverageNumberOfEmployeesInChinaAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    AverageNumberOfEmployeesInChinaAutoIndustry selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AverageNumberOfEmployeesInChinaAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业全部从业人员平均人数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AverageNumberOfEmployeesInChinaAutoIndustry record);
}