package com.citicup.dao;

import com.citicup.model.AmericanCarSales;
import com.citicup.model.CashFlowLiabilityRatioOfAutomobileEnterprisesInChina;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CashFlowLiabilityRatioOfAutomobileEnterprisesInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    int insert(CashFlowLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    int insertSelective(CashFlowLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    CashFlowLiabilityRatioOfAutomobileEnterprisesInChina selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CashFlowLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业现金流动负债比率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CashFlowLiabilityRatioOfAutomobileEnterprisesInChina record);

    @Select("SELECT * FROM citicup.中国汽车企业现金流动负债比率")
    List<CashFlowLiabilityRatioOfAutomobileEnterprisesInChina> getAll();
}