package com.citicup.dao;

import com.citicup.model.ChineseDomesticManufacturingProductionDividedByType;

public interface ChineseDomesticManufacturingProductionDividedByTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    int insert(ChineseDomesticManufacturingProductionDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseDomesticManufacturingProductionDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    ChineseDomesticManufacturingProductionDividedByType selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseDomesticManufacturingProductionDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分车型产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseDomesticManufacturingProductionDividedByType record);
}