package com.citicup.dao;

import com.citicup.model.ChineseDomesticManufacturingCommercialVehicleSalesByFuel;

public interface ChineseDomesticManufacturingCommercialVehicleSalesByFuelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    int insert(ChineseDomesticManufacturingCommercialVehicleSalesByFuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseDomesticManufacturingCommercialVehicleSalesByFuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    ChineseDomesticManufacturingCommercialVehicleSalesByFuel selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseDomesticManufacturingCommercialVehicleSalesByFuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车分燃料类型销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseDomesticManufacturingCommercialVehicleSalesByFuel record);
}