package com.citicup.dao;

import com.citicup.model.ChineseCarOwnershipPerOneThousandPeople;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ChineseCarOwnershipPerOneThousandPeopleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    int insert(ChineseCarOwnershipPerOneThousandPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseCarOwnershipPerOneThousandPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    ChineseCarOwnershipPerOneThousandPeople selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseCarOwnershipPerOneThousandPeople record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车每千人保有量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseCarOwnershipPerOneThousandPeople record);

    @Select("SELECT * FROM citicup.中国汽车每千人保有量")
    List<ChineseCarOwnershipPerOneThousandPeople> getAll();
}