package com.citicup.dao;

import com.citicup.model.ChineseDomesticManufacturingPassengerCarSalesDividedByType;

public interface ChineseDomesticManufacturingPassengerCarSalesDividedByTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    int insert(ChineseDomesticManufacturingPassengerCarSalesDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseDomesticManufacturingPassengerCarSalesDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    ChineseDomesticManufacturingPassengerCarSalesDividedByType selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseDomesticManufacturingPassengerCarSalesDividedByType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车分车型销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseDomesticManufacturingPassengerCarSalesDividedByType record);
}