package com.citicup.dao;

import com.citicup.model.ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction;

public interface ChineseMajorAutomobileGroupBasicPassengerVehiclesProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    int insert(ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国主要汽车集团基本型乘用车(轿车)产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseMajorAutomobileGroupBasicPassengerVehiclesProduction record);
}