package com.citicup.dao;

import com.citicup.model.ComparisonOfIndustryHistory_all;

public interface ComparisonOfIndustryHistory_allMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    int insert(ComparisonOfIndustryHistory_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfIndustryHistory_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    ComparisonOfIndustryHistory_all selectByPrimaryKey(String time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfIndustryHistory_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业历史比较-全部
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfIndustryHistory_all record);
}