package com.citicup.dao;

import com.citicup.model.CompanyBasicInformation;
import com.citicup.model.CompanyBasicInformationWithBLOBs;

public interface CompanyBasicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insert(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insertSelective(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    CompanyBasicInformationWithBLOBs selectByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyBasicInformation record);
}