package com.citicup.dao;

import com.citicup.model.ComparisonOfEarningsForecast_codeSplitTable;
import com.citicup.model.ComparisonOfEarningsForecast_codeSplitTableKey;

public interface ComparisonOfEarningsForecast_codeSplitTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ComparisonOfEarningsForecast_codeSplitTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    int insert(ComparisonOfEarningsForecast_codeSplitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfEarningsForecast_codeSplitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    ComparisonOfEarningsForecast_codeSplitTable selectByPrimaryKey(ComparisonOfEarningsForecast_codeSplitTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfEarningsForecast_codeSplitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较-代码+分表
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfEarningsForecast_codeSplitTable record);
}