package com.citicup.dao;

import com.citicup.model.CompanySizeRank;
import com.citicup.model.CompanySizeRankKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CompanySizeRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CompanySizeRankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    int insert(CompanySizeRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    int insertSelective(CompanySizeRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    CompanySizeRank selectByPrimaryKey(CompanySizeRankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanySizeRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司规模排序
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanySizeRank record);

    @Select("SELECT * FROM citicup.公司规模排序")
    List<CompanySizeRank> getAll();
}