package com.citicup.dao;

import com.citicup.model.CompanyClassification;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CompanyClassificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司分类
     *
     * @mbggenerated
     */
    int insert(CompanyClassification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司分类
     *
     * @mbggenerated
     */
    int insertSelective(CompanyClassification record);

    @Select("SELECT * FROM citicup.公司分类")
    List<CompanyClassification> getAll();
}