package com.citicup.dao;

import com.citicup.model.ComparisonOfValuationPerformance_otherAttributes;

public interface ComparisonOfValuationPerformance_otherAttributesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String securcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    int insert(ComparisonOfValuationPerformance_otherAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfValuationPerformance_otherAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    ComparisonOfValuationPerformance_otherAttributes selectByPrimaryKey(String securcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfValuationPerformance_otherAttributes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值表现分析-其他属性
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfValuationPerformance_otherAttributes record);
}