package com.citicup.dao;

import com.citicup.model.FixedAssetsInvestmentPriceIndexInChina;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface FixedAssetsInvestmentPriceIndexInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int insert(FixedAssetsInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int insertSelective(FixedAssetsInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    FixedAssetsInvestmentPriceIndexInChina selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FixedAssetsInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FixedAssetsInvestmentPriceIndexInChina record);

    @Select("SELECT * FROM citicup.中国固定资产投资价格指数")
    List<FixedAssetsInvestmentPriceIndexInChina> getAll();
}