package com.citicup.dao;

import com.citicup.model.Fixed-assetInvestmentPriceIndexInChina;

public interface Fixed-assetInvestmentPriceIndexInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int insert(Fixed-assetInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int insertSelective(Fixed-assetInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    Fixed-assetInvestmentPriceIndexInChina selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Fixed-assetInvestmentPriceIndexInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国固定资产投资价格指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Fixed-assetInvestmentPriceIndexInChina record);
}