package com.citicup.dao;

import com.citicup.model.GainPassengerCarOverallPriceChangeIndex;

public interface GainPassengerCarOverallPriceChangeIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    int insert(GainPassengerCarOverallPriceChangeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    int insertSelective(GainPassengerCarOverallPriceChangeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    GainPassengerCarOverallPriceChangeIndex selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GainPassengerCarOverallPriceChangeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体价格变化指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GainPassengerCarOverallPriceChangeIndex record);
}