package com.citicup.dao;

import com.citicup.model.GainPassengerCarOverallEndPreferentialIndex;

public interface GainPassengerCarOverallEndPreferentialIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    int insert(GainPassengerCarOverallEndPreferentialIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    int insertSelective(GainPassengerCarOverallEndPreferentialIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    GainPassengerCarOverallEndPreferentialIndex selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GainPassengerCarOverallEndPreferentialIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gain乘用车整体终端优惠指数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GainPassengerCarOverallEndPreferentialIndex record);
}