package com.citicup.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.citicup.model.Graph;

public class GraphSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph
     *
     * @mbggenerated
     */
    public String insertSelective(Graph record) {
        BEGIN();
        INSERT_INTO("graph");
        
        if (record.getGraphid() != null) {
            VALUES("graphId", "#{graphid,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        
        if (record.getUp() != null) {
            VALUES("up", "#{up,jdbcType=INTEGER}");
        }
        
        if (record.getDown() != null) {
            VALUES("down", "#{down,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graph
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Graph record) {
        BEGIN();
        UPDATE("graph");
        
        if (record.getAuthor() != null) {
            SET("author = #{author,jdbcType=VARCHAR}");
        }
        
        if (record.getUp() != null) {
            SET("up = #{up,jdbcType=INTEGER}");
        }
        
        if (record.getDown() != null) {
            SET("down = #{down,jdbcType=INTEGER}");
        }
        
        WHERE("graphId = #{graphid,jdbcType=VARCHAR}");
        
        return SQL();
    }
}