package com.citicup.dao;

import com.citicup.model.InventoryTurnoverRatio;
import com.citicup.model.InventoryTurnoverRatioKey;

public interface InventoryTurnoverRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(InventoryTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int insert(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int insertSelective(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    InventoryTurnoverRatio selectByPrimaryKey(InventoryTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryTurnoverRatio record);
}