package com.citicup.dao;

import com.citicup.model.NetProfitGrowthRate;
import com.citicup.model.NetProfitGrowthRateKey;

public interface NetProfitGrowthRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(NetProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int insert(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int insertSelective(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    NetProfitGrowthRate selectByPrimaryKey(NetProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NetProfitGrowthRate record);
}