package com.citicup.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.citicup.model.News;

public class NewsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public String insertSelective(News record) {
        BEGIN();
        INSERT_INTO("news");
        
        if (record.getStkcd() != null) {
            VALUES("stkcd", "#{stkcd,jdbcType=VARCHAR}");
        }
        
        if (record.getCompname() != null) {
            VALUES("compName", "#{compname,jdbcType=VARCHAR}");
        }
        
        if (record.getInfo() != null) {
            VALUES("info", "#{info,jdbcType=LONGVARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(News record) {
        BEGIN();
        UPDATE("news");
        
        if (record.getCompname() != null) {
            SET("compName = #{compname,jdbcType=VARCHAR}");
        }
        
        if (record.getInfo() != null) {
            SET("info = #{info,jdbcType=LONGVARCHAR}");
        }
        
        WHERE("stkcd = #{stkcd,jdbcType=VARCHAR}");
        
        return SQL();
    }
}