package com.citicup.dao;

import com.citicup.model.News;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @Delete({
        "delete from news",
        "where stkcd = #{stkcd,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @Insert({
        "insert into news (stkcd, compName, ",
        "info)",
        "values (#{stkcd,jdbcType=VARCHAR}, #{compname,jdbcType=VARCHAR}, ",
        "#{info,jdbcType=LONGVARCHAR})"
    })
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @InsertProvider(type=NewsSqlProvider.class, method="insertSelective")
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "stkcd, compName, info",
        "from news",
        "where stkcd = #{stkcd,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="stkcd", property="stkcd", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="compName", property="compname", jdbcType=JdbcType.VARCHAR),
        @Result(column="info", property="info", jdbcType=JdbcType.LONGVARCHAR)
    })
    News selectByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @UpdateProvider(type=NewsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @Update({
        "update news",
        "set compName = #{compname,jdbcType=VARCHAR},",
          "info = #{info,jdbcType=LONGVARCHAR}",
        "where stkcd = #{stkcd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbggenerated
     */
    @Update({
        "update news",
        "set compName = #{compname,jdbcType=VARCHAR}",
        "where stkcd = #{stkcd,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(News record);
}