package com.citicup.dao;

import com.citicup.model.OperatingMargin;
import com.citicup.model.OperatingMarginKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface OperatingMarginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OperatingMarginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    int insert(OperatingMargin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    int insertSelective(OperatingMargin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    OperatingMargin selectByPrimaryKey(OperatingMarginKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperatingMargin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业毛利率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperatingMargin record);

    @Select("SELECT * FROM citicup.营业毛利率")
    List<OperatingMargin> getAll();
}