package com.citicup.dao;

import com.citicup.model.OperatingCostRatio;
import com.citicup.model.OperatingCostRatioKey;

public interface OperatingCostRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OperatingCostRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    int insert(OperatingCostRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    int insertSelective(OperatingCostRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    OperatingCostRatio selectByPrimaryKey(OperatingCostRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperatingCostRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业成本率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperatingCostRatio record);
}