package com.citicup.dao;

import com.citicup.model.ProfitMarginOfTheCostAndExpense;
import com.citicup.model.ProfitMarginOfTheCostAndExpenseKey;

public interface ProfitMarginOfTheCostAndExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProfitMarginOfTheCostAndExpenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int insert(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int insertSelective(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    ProfitMarginOfTheCostAndExpense selectByPrimaryKey(ProfitMarginOfTheCostAndExpenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProfitMarginOfTheCostAndExpense record);
}