package com.citicup.dao;

import com.citicup.model.RevenueGrowth;
import com.citicup.model.RevenueGrowthKey;

public interface RevenueGrowthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(RevenueGrowthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    int insert(RevenueGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    int insertSelective(RevenueGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    RevenueGrowth selectByPrimaryKey(RevenueGrowthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RevenueGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业收入增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RevenueGrowth record);
}