package com.citicup.dao;

import com.citicup.model.TotalAssetsOfAutoIndustryInChina;

public interface TotalAssetsOfAutoIndustryInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    int insert(TotalAssetsOfAutoIndustryInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    int insertSelective(TotalAssetsOfAutoIndustryInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    TotalAssetsOfAutoIndustryInChina selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TotalAssetsOfAutoIndustryInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车行业资产总计
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TotalAssetsOfAutoIndustryInChina record);
}