package com.citicup.dao;

import com.citicup.model.TotalProfitGrowthRate;
import com.citicup.model.TotalProfitGrowthRateKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TotalProfitGrowthRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TotalProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    int insert(TotalProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    int insertSelective(TotalProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    TotalProfitGrowthRate selectByPrimaryKey(TotalProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TotalProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TotalProfitGrowthRate record);

    @Select("SELECT * FROM citicup.利润总额增长率")
    List<TotalProfitGrowthRate> getAll();
}