package com.citicup.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.citicup.model.User;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("user");
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=VARCHAR}");
        }
        
        if (record.getPhonenum() != null) {
            VALUES("phoneNum", "#{phonenum,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getIsbinded() != null) {
            VALUES("isBinded", "#{isbinded,jdbcType=TINYINT}");
        }
        
        if (record.getCitinum() != null) {
            VALUES("citiNum", "#{citinum,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=CHAR}");
        }
        
        if (record.getBirthday() != null) {
            VALUES("birthday", "#{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getIdnum() != null) {
            VALUES("idNum", "#{idnum,jdbcType=VARCHAR}");
        }
        
        if (record.getOccupation() != null) {
            VALUES("occupation", "#{occupation,jdbcType=VARCHAR}");
        }
        
        if (record.getOrganization() != null) {
            VALUES("organization", "#{organization,jdbcType=VARCHAR}");
        }
        
        if (record.getContactnum() != null) {
            VALUES("contactNum", "#{contactnum,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getSummary() != null) {
            VALUES("summary", "#{summary,jdbcType=VARCHAR}");
        }
        
        if (record.getCredit() != null) {
            VALUES("credit", "#{credit,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("user");
        
        if (record.getPhonenum() != null) {
            SET("phoneNum = #{phonenum,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getIsbinded() != null) {
            SET("isBinded = #{isbinded,jdbcType=TINYINT}");
        }
        
        if (record.getCitinum() != null) {
            SET("citiNum = #{citinum,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=CHAR}");
        }
        
        if (record.getBirthday() != null) {
            SET("birthday = #{birthday,jdbcType=VARCHAR}");
        }
        
        if (record.getIdnum() != null) {
            SET("idNum = #{idnum,jdbcType=VARCHAR}");
        }
        
        if (record.getOccupation() != null) {
            SET("occupation = #{occupation,jdbcType=VARCHAR}");
        }
        
        if (record.getOrganization() != null) {
            SET("organization = #{organization,jdbcType=VARCHAR}");
        }
        
        if (record.getContactnum() != null) {
            SET("contactNum = #{contactnum,jdbcType=VARCHAR}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getSummary() != null) {
            SET("summary = #{summary,jdbcType=VARCHAR}");
        }
        
        if (record.getCredit() != null) {
            SET("credit = #{credit,jdbcType=INTEGER}");
        }
        
        WHERE("uid = #{uid,jdbcType=VARCHAR}");
        
        return SQL();
    }
}