package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.AssetLiabilityRatio;
import com.citicup.model.dataDisplay.AssetLiabilityRatioKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AssetLiabilityRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AssetLiabilityRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    int insert(AssetLiabilityRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    int insertSelective(AssetLiabilityRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    AssetLiabilityRatio selectByPrimaryKey(AssetLiabilityRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetLiabilityRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 资产负债率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetLiabilityRatio record);

    @Select("SELECT * FROM citicup.资产负债率")
    List<AssetLiabilityRatio> getAll();
}