package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.AssetLiabilityRatioOfAutomobileEnterprisesInChina;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AssetLiabilityRatioOfAutomobileEnterprisesInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    int insert(AssetLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    int insertSelective(AssetLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    AssetLiabilityRatioOfAutomobileEnterprisesInChina selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetLiabilityRatioOfAutomobileEnterprisesInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业资产负债率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetLiabilityRatioOfAutomobileEnterprisesInChina record);

    @Select("SELECT * FROM citicup.中国汽车企业资产负债率")
    List<AssetLiabilityRatioOfAutomobileEnterprisesInChina> getAll();
}