package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.AutomobileIndustryBulletinInformation;
import com.citicup.model.dataDisplay.AutomobileIndustryBulletinInformationKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AutomobileIndustryBulletinInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AutomobileIndustryBulletinInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    int insert(AutomobileIndustryBulletinInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    int insertSelective(AutomobileIndustryBulletinInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    AutomobileIndustryBulletinInformation selectByPrimaryKey(AutomobileIndustryBulletinInformationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutomobileIndustryBulletinInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业公告信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutomobileIndustryBulletinInformation record);

    @Select("SELECT * FROM citicup.汽车行业公告信息")
    List<AutomobileIndustryBulletinInformation> getAll();
}