package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.AutomobileIndustryPolicyTrends;
import com.citicup.model.dataDisplay.AutomobileIndustryPolicyTrendsKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AutomobileIndustryPolicyTrendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AutomobileIndustryPolicyTrendsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int insert(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int insertSelective(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    AutomobileIndustryPolicyTrends selectByPrimaryKey(AutomobileIndustryPolicyTrendsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(AutomobileIndustryPolicyTrends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车行业政策动态
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AutomobileIndustryPolicyTrends record);

    @Select("SELECT * FROM citicup.汽车行业政策动态")
    List<AutomobileIndustryPolicyTrends> getAll();
}