package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprisesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    int insert(AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    int insertSelective(AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车企业三年销售平均增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises record);

    @Select("SELECT * FROM citicup.中国汽车企业三年销售平均增长率")
    List<AverageGrowthRateOfTheThreeYearSalesOfChineseAutoEnterprises> getAll();
}