package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.CarBusinessNews;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CarBusinessNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车企业新闻速览
     *
     * @mbggenerated
     */
    int insert(CarBusinessNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 汽车企业新闻速览
     *
     * @mbggenerated
     */
    int insertSelective(CarBusinessNews record);

    @Select("SELECT * FROM citicup.汽车企业新闻速览")
    List<CarBusinessNews> getAll();
}