package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ChineseCarDealerInventoryFactor;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ChineseCarDealerInventoryFactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    int insert(ChineseCarDealerInventoryFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    int insertSelective(ChineseCarDealerInventoryFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    ChineseCarDealerInventoryFactor selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseCarDealerInventoryFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国汽车经销商库存系数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseCarDealerInventoryFactor record);

    @Select("SELECT * FROM citicup.中国汽车经销商库存系数")
    List<ChineseCarDealerInventoryFactor> getAll();
}