package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ChineseDomesticManufacturingProduction;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ChineseDomesticManufacturingProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    int insert(ChineseDomesticManufacturingProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseDomesticManufacturingProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    ChineseDomesticManufacturingProduction selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseDomesticManufacturingProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造商用车产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseDomesticManufacturingProduction record);

    @Select("SELECT * FROM citicup.中国国内制造商用车产量")
    List<ChineseDomesticManufacturingProduction> getAll();
}