package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ChineseDomesticManufacturingPassengerCarProduction;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ChineseDomesticManufacturingPassengerCarProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    int insert(ChineseDomesticManufacturingPassengerCarProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    int insertSelective(ChineseDomesticManufacturingPassengerCarProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    ChineseDomesticManufacturingPassengerCarProduction selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChineseDomesticManufacturingPassengerCarProduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国国内制造乘用车产量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChineseDomesticManufacturingPassengerCarProduction record);

    @Select("SELECT * FROM citicup.中国国内制造乘用车产量")
    List<ChineseDomesticManufacturingPassengerCarProduction> getAll();

}