package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.CirculationMarketValueAndTotalMarketValue;
import com.citicup.model.dataDisplay.CirculationMarketValueAndTotalMarketValueKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CirculationMarketValueAndTotalMarketValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CirculationMarketValueAndTotalMarketValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    int insert(CirculationMarketValueAndTotalMarketValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    int insertSelective(CirculationMarketValueAndTotalMarketValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    CirculationMarketValueAndTotalMarketValue selectByPrimaryKey(CirculationMarketValueAndTotalMarketValueKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CirculationMarketValueAndTotalMarketValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流通市值与总市值
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CirculationMarketValueAndTotalMarketValue record);

    @Select("SELECT * FROM citicup.流通市值与总市值")
    List<CirculationMarketValueAndTotalMarketValue> getAll();
}