package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ComparisonOfEarningsForecast_sheet1;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ComparisonOfEarningsForecast_sheet1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String securcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    int insert(ComparisonOfEarningsForecast_sheet1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfEarningsForecast_sheet1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    ComparisonOfEarningsForecast_sheet1 selectByPrimaryKey(String securcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfEarningsForecast_sheet1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利预测比较sheet1
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfEarningsForecast_sheet1 record);

    @Select("SELECT * FROM citicup.盈利预测比较sheet1")
    List<ComparisonOfEarningsForecast_sheet1> getAll();
}