package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.CompanyBasicInformation;
import com.citicup.model.dataDisplay.CompanyBasicInformationWithBLOBs;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CompanyBasicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insert(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insertSelective(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    CompanyBasicInformationWithBLOBs selectByPrimaryKey(String stkcd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CompanyBasicInformation record);

    @Select("SELECT * FROM citicup.公司基本信息")
    List<CompanyBasicInformation> getAll();

    @Select("SELECT * FROM citicup.公司基本信息 WHERE stkcd = #{stkcd, jdbcType=VARCHAR}")
    List<CompanyBasicInformation> searchByStkcd(String stkcd);

    @Select("SELECT * FROM citicup.公司基本信息 WHERE compName = #{compName, jdbcType=VARCHAR}")
    List<CompanyBasicInformation> searchByName(String compName);

    @Select("SELECT * FROM citicup.公司基本信息 WHERE compName LIKE concat('%',#{compName, jdbcType=VARCHAR},'%')")
    List<CompanyBasicInformation> macthByName(String compName);

    @Select("SELECT * FROM citicup.公司基本信息 WHERE stkcd LIKE concat('%',#{stkcd, jdbcType=VARCHAR},'%')")
    List<CompanyBasicInformation> macthByStkcd(String stkcd);

}