package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ComparisonOfFinancialData_splitTable;
import com.citicup.model.dataDisplay.ComparisonOfFinancialData_splitTableKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ComparisonOfFinancialData_splitTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ComparisonOfFinancialData_splitTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    int insert(ComparisonOfFinancialData_splitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfFinancialData_splitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    ComparisonOfFinancialData_splitTable selectByPrimaryKey(ComparisonOfFinancialData_splitTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfFinancialData_splitTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务数据比较拆分表
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfFinancialData_splitTable record);

    @Select("SELECT * FROM citicup.财务数据比较拆分表")
    List<ComparisonOfFinancialData_splitTable> getAll();
}