package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.CompanyBasicInformationWithBLOBs;

public interface CompanyBasicInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insert(CompanyBasicInformationWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 公司基本信息
     *
     * @mbggenerated
     */
    int insertSelective(CompanyBasicInformationWithBLOBs record);
}