package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ComparisonOfFinancialRatio_all;
import com.citicup.model.dataDisplay.ComparisonOfFinancialRatio_allKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ComparisonOfFinancialRatio_allMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ComparisonOfFinancialRatio_allKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    int insert(ComparisonOfFinancialRatio_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    int insertSelective(ComparisonOfFinancialRatio_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    ComparisonOfFinancialRatio_all selectByPrimaryKey(ComparisonOfFinancialRatio_allKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ComparisonOfFinancialRatio_all record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 财务比率比较-全部
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ComparisonOfFinancialRatio_all record);

    @Select("SELECT * FROM citicup.财务比率比较-全部")
    List<ComparisonOfFinancialRatio_all> getAll();
}