package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ContrastOfMarketPerformance_shanghaiAndShenzhenAShares;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ContrastOfMarketPerformance_shanghaiAndShenzhenASharesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String indstnam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    int insert(ContrastOfMarketPerformance_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    int insertSelective(ContrastOfMarketPerformance_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    ContrastOfMarketPerformance_shanghaiAndShenzhenAShares selectByPrimaryKey(String indstnam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ContrastOfMarketPerformance_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 市场表现对比-沪深a股
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ContrastOfMarketPerformance_shanghaiAndShenzhenAShares record);

    @Select("SELECT * FROM citicup.市场表现对比-沪深a股")
    List<ContrastOfMarketPerformance_shanghaiAndShenzhenAShares> getAll();
}