package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.DaysInInventory;
import com.citicup.model.dataDisplay.DaysInInventoryKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface DaysInInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DaysInInventoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    int insert(DaysInInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    int insertSelective(DaysInInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    DaysInInventory selectByPrimaryKey(DaysInInventoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaysInInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转天数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaysInInventory record);

    @Select("SELECT * FROM citicup.存货周转天数")
    List<DaysInInventory> getAll();
}