package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.EquityTurnover;
import com.citicup.model.dataDisplay.EquityTurnoverKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface EquityTurnoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EquityTurnoverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    int insert(EquityTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    int insertSelective(EquityTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    EquityTurnover selectByPrimaryKey(EquityTurnoverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EquityTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 股东权益周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EquityTurnover record);

    @Select("SELECT * FROM citicup.股东权益周转率")
    List<EquityTurnover> getAll();
}