package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    int insert(GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    int insertSelective(GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry selectByPrimaryKey(String year);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 图形和数据导出中国汽车行业利润总额
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry record);

    @Select("SELECT * FROM citicup.图形和数据导出中国汽车行业利润总额")
    List<GraphicsAndDataDeriveTotalProfitsFromChinasAutoIndustry> getAll();
}