package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.GrowthRateOfOwnersEquity;
import com.citicup.model.dataDisplay.GrowthRateOfOwnersEquityKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface GrowthRateOfOwnersEquityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(GrowthRateOfOwnersEquityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    int insert(GrowthRateOfOwnersEquity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    int insertSelective(GrowthRateOfOwnersEquity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    GrowthRateOfOwnersEquity selectByPrimaryKey(GrowthRateOfOwnersEquityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GrowthRateOfOwnersEquity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 所有者权益增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GrowthRateOfOwnersEquity record);

    @Select("SELECT * FROM citicup.所有者权益增长率")
    List<GrowthRateOfOwnersEquity> getAll();
}