package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.HighwayPassengerTurnoverInChina;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface HighwayPassengerTurnoverInChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String month);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    int insert(HighwayPassengerTurnoverInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    int insertSelective(HighwayPassengerTurnoverInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    HighwayPassengerTurnoverInChina selectByPrimaryKey(String month);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HighwayPassengerTurnoverInChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 中国公路旅客周转量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HighwayPassengerTurnoverInChina record);

    @Select("SELECT * FROM citicup.中国公路旅客周转量")
    List<HighwayPassengerTurnoverInChina> getAll();
}