package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.InventoryTurnoverRatio;
import com.citicup.model.dataDisplay.InventoryTurnoverRatioKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface InventoryTurnoverRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(InventoryTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int insert(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int insertSelective(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    InventoryTurnoverRatio selectByPrimaryKey(InventoryTurnoverRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InventoryTurnoverRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryTurnoverRatio record);

    @Select("SELECT * FROM citicup.存货周转率")
    List<InventoryTurnoverRatio> getAll();
}