package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.NetProfitGrowthRate;
import com.citicup.model.dataDisplay.NetProfitGrowthRateKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface NetProfitGrowthRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(NetProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int insert(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int insertSelective(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    NetProfitGrowthRate selectByPrimaryKey(NetProfitGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NetProfitGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 净利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NetProfitGrowthRate record);

    @Select("SELECT * FROM citicup.净利润增长率")
    List<NetProfitGrowthRate> getAll();
}