package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.OperatingProfitGrowth;
import com.citicup.model.dataDisplay.OperatingProfitGrowthKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface OperatingProfitGrowthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OperatingProfitGrowthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    int insert(OperatingProfitGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    int insertSelective(OperatingProfitGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    OperatingProfitGrowth selectByPrimaryKey(OperatingProfitGrowthKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperatingProfitGrowth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业利润增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperatingProfitGrowth record);

    @Select("SELECT * FROM citicup.营业利润增长率")
    List<OperatingProfitGrowth> getAll();
}