package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.ProfitMarginOfTheCostAndExpense;
import com.citicup.model.dataDisplay.ProfitMarginOfTheCostAndExpenseKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ProfitMarginOfTheCostAndExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProfitMarginOfTheCostAndExpenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int insert(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int insertSelective(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    ProfitMarginOfTheCostAndExpense selectByPrimaryKey(ProfitMarginOfTheCostAndExpenseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProfitMarginOfTheCostAndExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProfitMarginOfTheCostAndExpense record);

    @Select("SELECT * FROM citicup.成本费用利润率")
    List<ProfitMarginOfTheCostAndExpense> getAll();
}