package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.RateOfReturnOnInvestment;
import com.citicup.model.dataDisplay.RateOfReturnOnInvestmentKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface RateOfReturnOnInvestmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(RateOfReturnOnInvestmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    int insert(RateOfReturnOnInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    int insertSelective(RateOfReturnOnInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    RateOfReturnOnInvestment selectByPrimaryKey(RateOfReturnOnInvestmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RateOfReturnOnInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 投资收益率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RateOfReturnOnInvestment record);

    @Select("SELECT * FROM citicup.投资收益率")
    List<RateOfReturnOnInvestment> getAll();
}