package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.StatusOfIndustryListing_shanghaiAndShenzhenAShares;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface StatusOfIndustryListing_shanghaiAndShenzhenASharesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String indstnam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    int insert(StatusOfIndustryListing_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    int insertSelective(StatusOfIndustryListing_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    StatusOfIndustryListing_shanghaiAndShenzhenAShares selectByPrimaryKey(String indstnam);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatusOfIndustryListing_shanghaiAndShenzhenAShares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 行业上市地位沪深a股
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatusOfIndustryListing_shanghaiAndShenzhenAShares record);

    @Select("SELECT * FROM citicup.行业上市地位沪深a股")
    List<StatusOfIndustryListing_shanghaiAndShenzhenAShares> getAll();
}