package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.TheGlobalCommercialVehicleSales;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TheGlobalCommercialVehicleSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    int insert(TheGlobalCommercialVehicleSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    int insertSelective(TheGlobalCommercialVehicleSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    TheGlobalCommercialVehicleSales selectByPrimaryKey(String f1);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TheGlobalCommercialVehicleSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 全球商用车销量
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TheGlobalCommercialVehicleSales record);

    @Select("SELECT * FROM citicup.全球商用车销量")
    List<TheGlobalCommercialVehicleSales> getAll();
}