package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.TotalOperatingCostGrowthRate;
import com.citicup.model.dataDisplay.TotalOperatingCostGrowthRateKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TotalOperatingCostGrowthRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TotalOperatingCostGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    int insert(TotalOperatingCostGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    int insertSelective(TotalOperatingCostGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    TotalOperatingCostGrowthRate selectByPrimaryKey(TotalOperatingCostGrowthRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TotalOperatingCostGrowthRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营业总成本增长率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TotalOperatingCostGrowthRate record);

    @Select("SELECT * FROM citicup.营业总成本增长率")
    List<TotalOperatingCostGrowthRate> getAll();
}