package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.TotalProfitPreTaxProfitRatio;
import com.citicup.model.dataDisplay.TotalProfitPreTaxProfitRatioKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TotalProfitPreTaxProfitRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TotalProfitPreTaxProfitRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    int insert(TotalProfitPreTaxProfitRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    int insertSelective(TotalProfitPreTaxProfitRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    TotalProfitPreTaxProfitRatio selectByPrimaryKey(TotalProfitPreTaxProfitRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TotalProfitPreTaxProfitRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 利润总额与息税前利润相比
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TotalProfitPreTaxProfitRatio record);

    @Select("SELECT * FROM citicup.利润总额与息税前利润相比")
    List<TotalProfitPreTaxProfitRatio> getAll();
}