package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.TurnoverOfCurrentAssets;
import com.citicup.model.dataDisplay.TurnoverOfCurrentAssetsKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TurnoverOfCurrentAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TurnoverOfCurrentAssetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    int insert(TurnoverOfCurrentAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    int insertSelective(TurnoverOfCurrentAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    TurnoverOfCurrentAssets selectByPrimaryKey(TurnoverOfCurrentAssetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TurnoverOfCurrentAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 流动资产周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TurnoverOfCurrentAssets record);

    @Select("SELECT * FROM citicup.流动资产周转率")
    List<TurnoverOfCurrentAssets> getAll();
}