package com.citicup.dao.dataDisplay;

import com.citicup.model.dataDisplay.WorkingCapitalAndLoanRatio;
import com.citicup.model.dataDisplay.WorkingCapitalAndLoanRatioKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface WorkingCapitalAndLoanRatioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(WorkingCapitalAndLoanRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    int insert(WorkingCapitalAndLoanRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    int insertSelective(WorkingCapitalAndLoanRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    WorkingCapitalAndLoanRatio selectByPrimaryKey(WorkingCapitalAndLoanRatioKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkingCapitalAndLoanRatio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 营运资金与借款比
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WorkingCapitalAndLoanRatio record);

    @Select("SELECT * FROM citicup.营运资金与借款比")
    List<WorkingCapitalAndLoanRatio> getAll();
}