package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.ConsistenceExpectationPredictProfit;

public interface ConsistenceExpectationPredictProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期预测营业收入
     *
     * @mbggenerated
     */
    int insert(ConsistenceExpectationPredictProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期预测营业收入
     *
     * @mbggenerated
     */
    int insertSelective(ConsistenceExpectationPredictProfit record);
}