package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.ConsistenceExpectationPredictProfit;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ConsistenceExpectationPredictProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期预测营业收入
     *
     * @mbggenerated
     */
    int insert(ConsistenceExpectationPredictProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期预测营业收入
     *
     * @mbggenerated
     */
    int insertSelective(ConsistenceExpectationPredictProfit record);

    @Select("SELECT * FROM citicup.分析师类-一致预期预测营业收入")
    List<ConsistenceExpectationPredictProfit> getAll();
}