package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.ConsistenceExpectation;

public interface ConsistenceExpectationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期pb
     *
     * @mbggenerated
     */
    int insert(ConsistenceExpectation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类-一致预期pb
     *
     * @mbggenerated
     */
    int insertSelective(ConsistenceExpectation record);
}