package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.CostProfitMarginCumu;
import com.citicup.model.correlationAnalysis.CostProfitMarginCumuKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CostProfitMarginCumuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CostProfitMarginCumuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    int insert(CostProfitMarginCumu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    int insertSelective(CostProfitMarginCumu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    CostProfitMarginCumu selectByPrimaryKey(CostProfitMarginCumuKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CostProfitMarginCumu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量累计成本费用利润率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CostProfitMarginCumu record);

    @Select("SELECT * FROM citicup.盈利质量累计成本费用利润率")
    List<CostProfitMarginCumu> getAll();
}