package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.DealersNumChange_1M;
import com.citicup.model.correlationAnalysis.DealersNumChange_1MKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface DealersNumChange_1MMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DealersNumChange_1MKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    int insert(DealersNumChange_1M record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    int insertSelective(DealersNumChange_1M record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    DealersNumChange_1M selectByPrimaryKey(DealersNumChange_1MKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DealersNumChange_1M record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 分析师类最近一个月券商覆盖数量券商家数变化
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DealersNumChange_1M record);

    @Select("SELECT * FROM citicup.分析师类最近一个月券商覆盖数量券商家数变化 WHERE value is not NULL")
    List<DealersNumChange_1M> getAll();
}