package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.DividendRate;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface DividendRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-股息率
     *
     * @mbggenerated
     */
    int insert(DividendRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-股息率
     *
     * @mbggenerated
     */
    int insertSelective(DividendRate record);

    @Select("SELECT * FROM citicup.估值类-股息率")
    List<DividendRate> getAll();
}