package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.DividendRate;
import com.citicup.model.correlationAnalysis.DividendRateKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface DividendRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DividendRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    int insert(DividendRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    int insertSelective(DividendRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    DividendRate selectByPrimaryKey(DividendRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DividendRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类股息率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DividendRate record);

    @Select("SELECT * FROM citicup.估值类股息率 WHERE value is not NULL")
    List<DividendRate> getAll();
}