package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.IncometaxProfitPercent;

public interface IncometaxProfitPercentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量-所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int insert(IncometaxProfitPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量-所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int insertSelective(IncometaxProfitPercent record);
}