package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.IncometaxProfitPercent;
import com.citicup.model.correlationAnalysis.IncometaxProfitPercentKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface IncometaxProfitPercentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(IncometaxProfitPercentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int insert(IncometaxProfitPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int insertSelective(IncometaxProfitPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    IncometaxProfitPercent selectByPrimaryKey(IncometaxProfitPercentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IncometaxProfitPercent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 盈利质量所得税占盈利总额百分比
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IncometaxProfitPercent record);

    @Select("SELECT * FROM citicup.盈利质量所得税占盈利总额百分比 WHERE value is not NULL")
    List<IncometaxProfitPercent> getAll();
}