package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.InventoryTurnover;
import com.citicup.model.correlationAnalysis.InventoryTurnoverKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface InventoryTurnoverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(InventoryTurnoverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    int insert(InventoryTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    int insertSelective(InventoryTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    InventoryTurnover selectByPrimaryKey(InventoryTurnoverKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InventoryTurnover record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性存货周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InventoryTurnover record);

    @Select("SELECT * FROM citicup.安全性存货周转率")
    List<InventoryTurnover> getAll();
}