package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.MarketSellingRateRec;
import com.citicup.model.correlationAnalysis.MarketSellingRateRecKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface MarketSellingRateRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MarketSellingRateRecKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    int insert(MarketSellingRateRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    int insertSelective(MarketSellingRateRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    MarketSellingRateRec selectByPrimaryKey(MarketSellingRateRecKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MarketSellingRateRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类市销率的倒数
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MarketSellingRateRec record);

    @Select("SELECT * FROM citicup.估值类市销率的倒数")
    List<MarketSellingRateRec> getAll();
}