package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.PE_history;
import com.citicup.model.correlationAnalysis.PE_historyKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface PE_historyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PE_historyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    int insert(PE_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    int insertSelective(PE_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    PE_history selectByPrimaryKey(PE_historyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PE_history record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PE_history record);

    @Select("SELECT * FROM citicup.pe_history")
    List<PE_history> getAll();
}