package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.PE_RatioRec;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface PE_RatioRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-市盈率的倒数
     *
     * @mbggenerated
     */
    int insert(PE_RatioRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-市盈率的倒数
     *
     * @mbggenerated
     */
    int insertSelective(PE_RatioRec record);

    @Select("SELECT * FROM citicup.估值类-市盈率的倒数")
    List<PE_RatioRec> getAll();
}