package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.PE_RatioRec;

public interface PE_RatioRecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-市盈率的倒数
     *
     * @mbggenerated
     */
    int insert(PE_RatioRec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 估值类-市盈率的倒数
     *
     * @mbggenerated
     */
    int insertSelective(PE_RatioRec record);
}