package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.stockNetProfits;
import com.citicup.model.correlationAnalysis.stockNetProfitsKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface stockNetProfitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(stockNetProfitsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    int insert(stockNetProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    int insertSelective(stockNetProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    stockNetProfits selectByPrimaryKey(stockNetProfitsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(stockNetProfits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stocknetprofits
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(stockNetProfits record);

    @Select("SELECT * FROM citicup.stocknetprofits")
    List<stockNetProfits> getAll();
}