package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.stockPrice;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface stockPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockprice
     *
     * @mbggenerated
     */
    int insert(stockPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stockprice
     *
     * @mbggenerated
     */
    int insertSelective(stockPrice record);

    @Select("SELECT * FROM citicup.stockprice")
    List<stockPrice> getAll();

    @Select("SELECT * FROM citicup.stockprice s GROUP BY s.date ORDER BY stkcd ASC")
    List<stockPrice> getGroupsBy();
}