package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.TenoreRatio_60D;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TenoreRatio_60DMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量-60日特诺雷比率
     *
     * @mbggenerated
     */
    int insert(TenoreRatio_60D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量-60日特诺雷比率
     *
     * @mbggenerated
     */
    int insertSelective(TenoreRatio_60D record);

    @Select("SELECT * FROM citicup.价量-60日特诺雷比率")
    List<TenoreRatio_60D> getAll();
}