package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.TenoreRatio_20D;
import com.citicup.model.correlationAnalysis.TenoreRatio_20DKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TenoreRatio_20DMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TenoreRatio_20DKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    int insert(TenoreRatio_20D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    int insertSelective(TenoreRatio_20D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    TenoreRatio_20D selectByPrimaryKey(TenoreRatio_20DKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TenoreRatio_20D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量20日特诺雷比率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TenoreRatio_20D record);

    @Select("SELECT * FROM citicup.价量20日特诺雷比率")
    List<TenoreRatio_20D> getAll();
}