package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.TurnoverOfTotalAssets;

public interface TurnoverOfTotalAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类-总资产周转率
     *
     * @mbggenerated
     */
    int insert(TurnoverOfTotalAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类-总资产周转率
     *
     * @mbggenerated
     */
    int insertSelective(TurnoverOfTotalAssets record);
}