package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.TurnoverOfTotalAssets;
import com.citicup.model.correlationAnalysis.TurnoverOfTotalAssetsKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TurnoverOfTotalAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TurnoverOfTotalAssetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    int insert(TurnoverOfTotalAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    int insertSelective(TurnoverOfTotalAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    TurnoverOfTotalAssets selectByPrimaryKey(TurnoverOfTotalAssetsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TurnoverOfTotalAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 安全性类总资产周转率
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TurnoverOfTotalAssets record);

    @Select("SELECT * FROM citicup.安全性类总资产周转率 WHERE value is not NULL")
    List<TurnoverOfTotalAssets> getAll();
}