package com.citicup.dao.correlationAnalysis;

import com.citicup.model.correlationAnalysis.TurnoverStd_6D;
import com.citicup.model.correlationAnalysis.TurnoverStd_6DKey;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TurnoverStd_6DMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TurnoverStd_6DKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    int insert(TurnoverStd_6D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    int insertSelective(TurnoverStd_6D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    TurnoverStd_6D selectByPrimaryKey(TurnoverStd_6DKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TurnoverStd_6D record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 价量6日成交额标准差
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TurnoverStd_6D record);

    @Select("SELECT * FROM citicup.价量6日成交额标准差")
    List<TurnoverStd_6D> getAll();
}